### ISSUE TITLE
`object` support?

### ISSUE THREAD

**Issue by zvaehn** [verlok/vanilla-lazyload#177]
How about supporting the object-tag?
I am currently using this library for images and i would love to use it for svgs inside objects as well.

**Comment by verlok** [comment]
Hi @zvaehn,
Thank you for the suggestion!

To better understand your request, could you post here the snippet of HTML code you would use?

Thanks

**Comment by zvaehn** [comment]
```php
<object type="image/svg+xml" data="image.svg"></object>
```

`data` has to be set and the value could be provided over the already existing `data_src`.
The type could vary in different use-cases, but this should not be relevant, is it?

**Comment by verlok** [comment]
That would make sense, but I never saw an SVG used like that. Are you sure it works?

I tried it on [this Pen](https://codepen.io/verlok/pen/wyomjO), both with the `src` and the `data` set, but I can't see the image displayed.

```html
<object type="image/svg+xml" src="http://simpleicon.com/wp-content/uploads/mail-5.svg"></object>
```

On the other hand, the svg file as source of an `img` tag works. Like:

```html
<img src="http://simpleicon.com/wp-content/uploads/mail-5.svg"></img>
```

So why don't use the img tag to lazily load SVGs too?

**Comment by zvaehn** [comment]
I think there is an issue with the svg you are using.
I forked [your pen](https://codepen.io/hiimzvaehn/pen/NydWOV) and it just works fine :)

The object-tag is more flexible than the img-tag.
For example: I am using a custom font inside the svg
![custom-font](https://user-images.githubusercontent.com/5555821/35969864-8af7b770-0cc8-11e8-9950-3444b0131b28.png)

If you are using the img-tag, the font cannot be loaded.

**Comment by verlok** [comment]
It probably was a mixed-content issue, due to the fact that codepen is on https and the image was your

**Comment by verlok** [comment]
...was on http. Thanks for fixing that.
I’ll take a look to the code to see how easy is to change the destination attribute to `data`. It shouldn’t be a big deal.

**Comment by verlok** [comment]
Still here. 
Sorry for taking that long, bad time. 
Will work on this ASAP. 
Many thanks for your patience.

**Comment by verlok** [comment]
Hi @matheusdigital 
I’ve updated you comment escaping the html tags with the backticks (`) because they weren’t visible to the readers before.

**Comment by verlok** [comment]
What exactly do you need to do with the `object` tag?

**Comment by verlok** [comment]
I understand your request now. 

So you would like something like this:

```
<object type="image/svg+xml" 
        class="object" 
        data-data="https://greensock.com/wp-content/themes/greensock/images/icon-github.svg">
</object>
```

To become the following when it enters the viewport

```
<object type="image/svg+xml" 
        class="object" 
        data="https://greensock.com/wp-content/themes/greensock/images/icon-github.svg">
</object>
```

Is that correct?

**Comment by matheusdigital** [comment]
@verlok Exactly! 

I managed how to get that with the following JS code. But I guess you could implement something similar onto your lib :)

<object class="lazy" type="image/svg+xml" data-object="https://greensock.com/wp-content/themes/greensock/images/icon-github.svg"></object>

`var svgObject = element.target.getAttribute('data-object');
 if (svgObject) {
    element.target.setAttribute('data', svgObject);
 }`

**Comment by verlok** [comment]
(I edited your comment above, if you edit it again you will see how to format code blocks)

**Comment by verlok** [comment]
Yes I will implement this in LazyLoad.
It should be quite an easy task.

**Comment by verlok** [comment]
The only thing I'm still not understanding is: I never used the `object` tag to load SVGs.
I'm investigating if this can be done using the the `svg` tag instead, and loading an external source.

**Comment by verlok** [comment]
Anyway since I see the `object` tag can be used to display also PDFs and other stuff, I guess I will just implement it for the `object` tag, then eventually extend it to the `svg` tag.

**Comment by verlok** [comment]
When I googled a bit to see if I could use the `svg` tag, I've found this script [external-svg-loader](https://www.npmjs.com/package/external-svg-loader) that you could find useful.

Here's a [CSS-tricks article](https://css-tricks.com/svg-loader-a-different-way-to-work-with-external-svg/) which shows how to use it.

So for now I will only work on lazy loading the `object` tag.

**Comment by verlok** [comment]
So for now I will only work on lazy loading the `object` tag, which can be useful to load anything.

**Comment by matheusdigital** [comment]
Yes, agree. Thanks for looking into it and all the clear information, @verlok!

**Comment by verlok** [comment]
Feature added! See documentation and version 17.6.0.
@matheusdigital let me know if it works for your case!

**Comment by verlok** [comment]
@matheusdigital did you have the chance to try it?

**Comment by verlok** [comment]
@matheusdigital ?

**Comment by verlok** [comment]
@zvaehn would you be able to try this to lazyload your external SVGs with an `object` tag?

**Comment by verlok** [comment]
@matheusdigital did you have any chance to try it out?

**Comment by verlok** [comment]
@zvaehn , @matheusdigital 
did you get the chance to try the new version with object support?

**Comment by verlok** [comment]
Hey @zvaehn, @matheusdigital 

I didn't get any feedback 😞, but I'm closing this issue assuming it works. Feel free to reopen in case you need anything.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
