### ISSUE TITLE
Provide a new version for cdnjs.cloudflare.com.

### ISSUE THREAD

**Issue by Github-XiaoFei** [verlok/vanilla-lazyload#444]
As you can see, the latest version (15.1.1) does not exist on the CDN page:
https://cdnjs.com/libraries/vanilla-lazyload

I know that the latest version can be found at cdn.jsdelivr.net, but my webpage uses cloudflare scripts. I do n’t want to parse the domain name of jsdelivr.net. Hope you can support cdnjs.cloudflare with a new version.

Thanks for this great script.

**Comment by verlok** [comment]
Hey there. I started using jsdelivr just because cdnjs stopped working and they weren’t giving support to me. I will try again.

**Comment by verlok** [comment]
I found [a number of issues](https://github.com/cdnjs/cdnjs/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%93%A6+Update+Request%22) on the CDNJS repo about packages not being updated.
I will add mine too now.

**Comment by verlok** [comment]
@Github-XiaoFei if you are in a hurry, you can do a pull request to CDNJS, the procedure can be found [here](https://github.com/cdnjs/cdnjs/issues/13903).

**Comment by Github-XiaoFei** [comment]
Thanks, I get it. I will continue to wait.

**Comment by verlok** [comment]
See #13903

**Comment by verlok** [comment]
All versions of vanilla-lazyload are now on CDNJS too. 

🎉👍🏼

**Comment by Github-XiaoFei** [comment]
Sorry, late reply.
Thank you for your help. 🎉🎉🎉
