### ISSUE TITLE
Stuck at 'loading' in Safari 13 when using 'src'

### ISSUE THREAD

**Issue by dithom** [verlok/vanilla-lazyload#463]
**Describe the bug**
In Safari 13.0.5 images are stuck at 'loading' and don't get the 'loaded' class even though they are loaded by the browser **as long as I have a 'src' attribute set**. If I inspect the assets in the network tab, Safari says it's getting them from storage, I think that means cache? But even if I empty the cache and the images are loaded by request, the class does not switch. All is working fine in Chrome, Firefox and even IE11. Lazy images way down at the bottom are loaded successfully though when they are in viewport. For me it looks a lot like some Safari caching stuff, thats breaking the lazy load here... I'm using 'src', so the images can be crawled by searchbots, so I don't really want to just remove it. Thanks!

**To Reproduce**

My html:
```
<img class="lazy"
src="someSrcInLowRes"
data-src="someSrc"
data-srcset="someSrcSet"
data-sizes="100vw"
alt="someAlt"
title="someTitle">
```

My js:
```
import LazyLoad from 'vanilla-lazyload';

const lazyLoad = new LazyLoad({
  elements_selector: '.lazy'
});
```

**Expected behavior**
Class should switch to 'loaded' when image is loaded.

**LazyLoad version**
- Version 16.1.0

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Safari
 - Version 13.0.5

**Screenshots**
<img width="766" alt="Bildschirmfoto 2020-06-01 um 14 02 37" src="https://user-images.githubusercontent.com/12197549/83407255-9c7b9c00-a410-11ea-8149-de2bb8cd53ea.png">

**Comment by twwli** [comment]
Same unexpected behavior happens on Firefox (using "src" as well).

OS: macOS
Browser Firefox
Version 176.0.1

**Comment by verlok** [comment]
It might be a browser bug due to the fact that the load event has been fired already when the image in the `src` attribute is first loaded. I’ll investigate further.

**Comment by verlok** [comment]
I've just tried the `demos/image_ph_inline.html` in Safari 13.1 Mac.

Before lazy load
![image](https://user-images.githubusercontent.com/1127721/83955467-85dfa580-a853-11ea-8100-b8c774752962.png)

After lazy load
![image](https://user-images.githubusercontent.com/1127721/83955481-a60f6480-a853-11ea-800f-ab456840efa3.png)

All OK

**Comment by verlok** [comment]
I've also tried the `/demos/image_ph_external.html` demo, same results, nothing gets stuck in the `loading` state.
![image](https://user-images.githubusercontent.com/1127721/83955532-1f0ebc00-a854-11ea-80ae-01d88f99d152.png)

**Comment by verlok** [comment]
So I can't reproduce the bug.
Also because I can't run that specific version os Safari, neither on Browserstack.
Can you create a Codepen and share it so I can reproduce the bug too?
Or tell me on which website I can reproduce it?

**Comment by dithom** [comment]
Here is a pen with the logic I'm using, but I can't reproduce the issue in codepen.
https://codepen.io/tomtomd/pen/MWKwzNb
I've sent you an email with a link to the environment having the issue. Hope you can reproduce it there.

**Comment by dithom** [comment]
> It might be a browser bug due to the fact that the load event has been fired already when the image in the `src` attribute is first loaded. I’ll investigate further.

I thought of this as well. I now was able to track it down to the following: If I use a "src" that is not used inside the "data-srcset" attribute, Safari is forced to replace the image and the load event is fired. If I use a "src" that is also used in the "data-srcset" and the viewport is at a width which will request the same resource as set in "src", **Safari won't fire an event.**

The only fix I can think of is comparing "src" and the requested resource in "data-srcset" and set the class to "loaded", if they are the same. But that will leave out the onload event.

**Comment by verlok** [comment]
That’s exactly the solution I was about to suggest to you. 

I’m glad you solved!

**Comment by verlok** [comment]
I hope you’re satisfied with my support. Please [let me know](https://ko-fi.com/verlok) if you are. 
If you still need help, I’m here.

**Comment by dithom** [comment]
> I hope you’re satisfied with my support. Please [let me know](https://ko-fi.com/verlok) if you are.
> If you still need help, I’m here.

Absolutely! Thanks, great work on this library! 👍💪

**Comment by verlok** [comment]
Hey @dithom,
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 

Have a nice day!

**Comment by patrickroppel** [comment]
dear all

i stumbled on this conversation and it seems that I am suffering from the same problem, even though I am using a different lazy loading script. 

on safari, when I navigate on my site to a subpage, the images load but don't show. only when I resize the window or reload, they appear instantly.  i looked at the above solution but not sure on how I could make it work with my set up. 

i would be very grateful if anyone has an idea on how I could go about this? very happy to buy coffees if that helps.

**Comment by dithom** [comment]
Hi @patrickroppel it seems you are using swup in your project (https://github.com/swup). My guess would be, that your lazy load script is initialized on page load only. When using ajax to replace the content of your site, the lazy load script needs to be initialized again after the content has been replaced. I have no idea, why its working in other browsers though. Maybe Safari is very efficient regarding image loading. Very nice design btw!

**Comment by patrickroppel** [comment]
hi dithom. thank you very much for getting back to me. and thank you as well for the compliment. unfortunately I am much better at design than javascript. i thought I am loading the script after the page is loaded. 

![Screenshot 2021-04-01 at 12 08 30](https://user-images.githubusercontent.com/49479054/113280073-2243ce80-92e4-11eb-9ef5-5ad35cb8714f.jpg)

shouldn't this be doing it? sorry, I am really lost with this...

**Comment by dithom** [comment]
@patrickroppel I guess we should change to another way of communication as this has nothing to do with this repository. I will send you an email.
