### ISSUE TITLE
Using Lazyload with AJAX REST api call

### ISSUE THREAD

**Issue by JORGEMAL** [verlok/vanilla-lazyload#464]
I have successfully implemented Vanilla Lazyload in one of my pages of my website. However, my website contains a page that depends on an AJAX call to a web service (a REST api) and the final HTML page is composed in javascript code. In this case, the images with "data-src" are not loaded. 

Is it possible to use Lazyload in this way?

Respectfully,
Jorge Maldonado

**Comment by verlok** [comment]
Yes @JORGEMAL ,
please read the "Dynamic content" section of the readme, [here](https://github.com/verlok/vanilla-lazyload#dynamic-content).
There you will find the explanation, the links to the demo, the code and the API doc.
Please let me know if this [helped](https://ko-fi.com/verlok).

**Comment by JORGEMAL** [comment]
Hi,

Thanks for your reply.
I have implemented the "Dynamic Content" workaround and it works just great.

Respectfully,
Jorge Maldonado

**Comment by verlok** [comment]
Hola @JORGEMAL 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 

Have a nice day!
