### ISSUE TITLE
Using an async script + getting multiple instance references

### ISSUE THREAD

**Issue by LeaTark** [verlok/vanilla-lazyload#466]
Do you have an example that combines multiple configurations with getting the reference?

Thanks.

**Comment by verlok** [comment]
Hi,
can you be more specific with what are you trying to do and where do you need help?

**Comment by LeaTark** [comment]
I was following your example "Using an async script"
https://github.com/verlok/vanilla-lazyload#using-an-async-script
and noted "You can pass:... an array of objects to get multiple instances of LazyLoad, each one with different options"

Then looked at the example "Using an async script + getting the instance reference"
https://github.com/verlok/vanilla-lazyload#using-an-async-script--getting-the-instance-reference
However, that example only seems to cater for a single instance, is that right?

window.addEventListener(
  "LazyLoad::Initialized",
  function (event) {
    window.lazyLoadInstance = event.detail.instance;
  },
  false
);

**Comment by verlok** [comment]
Yes, you're correct.
Now I get what you were asking with the sentence:

> Do you have an example that combines multiple configurations with getting the reference?

So you would like to create N `async` instances of LazyLoad, get all their references, and use them.
I can help you find the solution here, it's no that hard, but can I ask you a question before?
Why do you need N different instances? Are you sure you can't use only one?

**Comment by verlok** [comment]
Hey again @LeaTark,

I've been working on it and I've created a new [DEMO](https://www.andreaverlicchi.eu/vanilla-lazyload/demos/async_multiple.html) for multiple `async` LazyLoad instances.
Check out the [SOURCE](https://github.com/verlok/vanilla-lazyload/blob/master/demos/async_multiple.html) here.

Let me know if this is what you were looking after.

**Comment by theronniedsouza** [comment]
I also tried the same but for me all the images are fetched on page load.

 <script>
    window.lazyLoadInstances = [];
    window.lazyLoadOptions = { container: document.querySelector('.lazy-load-container') };
    window.addEventListener(
    "LazyLoad::Initialized",
    function (e) {
      var instance = e.detail.instance;
      console.log(instance);
      lazyLoadInstances.push(instance);
    }, false);
  </script>
  <script async src="js/lazyload.min.js"></script>

**Comment by theronniedsouza** [comment]
For me it is failing. All the images are fetched on load.

` <script>
    window.lazyLoadInstances = [];
    window.lazyLoadOptions = { container: document.querySelector('.lazy-load-container') };
    window.addEventListener(
    "LazyLoad::Initialized",
    function (e) {
      var instance = e.detail.instance;
      console.log(instance);
      lazyLoadInstances.push(instance);
    }, false);
  </script>
  <script async src="js/lazyload.min.js"></script>`

**Comment by verlok** [comment]
@theronniedsouza this issue is not about a bug, if you’d like to report a bug please open a new issue and I’ll support you. Thanks

@LeaTark did you have any change to look at it?

**Comment by verlok** [comment]
@LeaTark ?

**Comment by LeaTark** [comment]
Sorry, no, I didn't get chance to try it yet.
But it looks like you've given me exactly what I needed so thank you.

**Comment by verlok** [comment]
Thanks, @LeaTark.
I'm closing this now.
If you need any additional support, just let me know.
