### ISSUE TITLE
Attribute data-bg combined with media queries or width

### ISSUE THREAD

**Issue by mihail-minkov** [verlok/vanilla-lazyload#467]
**Is your feature request related to a problem? Please describe.**

I frequently use backgrounds on `div` elements, but many times I need to select a specific image size for a specific media query. I normally do this using breakpoints in my CSS file, but it doesn't load lazily :) 

**Describe the solution you'd like**

Something similar to `data-bg`, except that the information in `data-bg` could be a JSON array with background objects having two parameters: `media` and `image`.

Something like:

```html
<div 
  class="lazy" 
  data-bg-list="[
    {media: 'max-width: 640px', image: '/img/small.jpg'}, 
    {media: 'min-width: 641px', image: '/img/medium.jpg'}, 
    {media: 'min-width: 1025px', image: '/img/large.jpg'}
  ]">
</div>
```

The idea could also apply to `data-bg-hidpi`.

**Comment by fienen** [comment]
I don't have anything to add here except a +1 to the idea. I was literally just researching whether or not the tool could support this because I'm replacing markup that's set up the same way.

**Comment by LeaTark** [comment]
No doubt not the best way to do it but this is how I use lazyload to get responsive lazy backgrounds.

Not just backgrounds, I trigger all manner of effects this way.


<style>
  @media (max-width: 767.98px) {#mydiv.lazy-loaded {background-image: url("big.jpg");}}
  @media (min-width: 768px) {#mydiv.lazy-loaded  {background-image: url("small.jpeg");}}
</style>


<div id="mydiv" data-lazy-css></div>


<script>
  window.llStyles = new LazyLoad({
    elements_selector: "[data-lazy-css]",
    threshold: 0,
    unobserve_entered: true,
    callback_enter: function (element) {
      element.classList.add('lazy-loaded');
    }
  });
</script>

**Comment by mihail-minkov** [comment]
@LeaTark that looks interesting. So you basically add the styles for each background inside the file and then by adding the class you force the background to load?

What other applications do you refer to?

**Comment by LeaTark** [comment]
@mihail-minkov, yes, the images in the media queries aren't loaded until the rule finds a match, which only happens after lazyload adds a class.

I use the same method to trigger css animations and other effects when elements enter viewport, e.g. sheen effects to draw attention to calls to action.

This is why I set threshold: 0, so the effects are only applied when the element is in viewport and not before.

**Comment by verlok** [comment]
Thanks @mihail-minkov for the idea, I'll think about it. 

The implementation that @LeaTark is suggesting is also interesting. Congrats!

Sorry guys for the late reply, I'm on my annual leave (holidays with family).

**Comment by andre-brdoch** [comment]
Is there any news on this one? 😄 this feature would allow for great performance improvments

**Comment by verlok** [comment]
Hello guys,
hello @andre-brdoch 

The solution to this specific problem is the one @LeaTark posted [above](https://github.com/verlok/vanilla-lazyload/issues/467#issuecomment-652274626), which can also be used to solve other situation.

I think that adding the logic that @mihail-minkov proposed in the first message would be of a good use, but it would pollute the HTML code too much, whereas using @LeaTark's solution you can move the use cases to your Javascript code, and reuse much of it.

So if it's ok to you guys, I would close this issue since it already has a solution.

**Comment by verlok** [comment]
Hello guys,
sorry again for the latency, 2020 wasn't good and 2021 turned to be quite 👨‍👩‍👧‍👦... busy!  

@mihail-minkov thank you for opening this discussion and @LeaTark thank you for your valid contribution!
@andre-brdoch, @fienen I hope you managed to improve your performance this way!

I encourage you all to also take a look to the code I provided in the [lazy functions recipe](https://github.com/verlok/vanilla-lazyload#lazy-functions) on the documentation, which I'm pasting here for your convenience.

```js
// It's a best practice to scope the function names inside a namespace like `lazyFunctions`.
window.lazyFunctions = {
  foo: function (element) {
    element.style.color = "red";
    console.log("foo");
  },
  bar: function (element) {
    element.remove(element);
    console.log("bar");
  },
  buzz: function (element) {
    var span = document.createElement("span");
    span.innerText = " - buzz!";
    element.appendChild(span);
    console.log("buzz");
  },
  booya: function (element) {
    element.classList.add("boo");
    console.log("booya");
  }
};

function executeLazyFunction(element) {
  var lazyFunctionName = element.getAttribute("data-lazy-function");
  var lazyFunction = window.lazyFunctions[lazyFunctionName];
  if (!lazyFunction) return;
  lazyFunction(element);
}

var ll = new LazyLoad({
  unobserve_entered: true, // <- Avoid executing the function multiple times
  callback_enter: executeLazyFunction // Assigning the function defined above
});
```

I think that's a clever way to do anything you want using the simplicity of the abstraction granted by this lazyload script.

**Comment by verlok** [comment]
With that comment, @fienen, @andre-brdoch, @mihail-minkov, and @LeaTark I think I'm closing this issue.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!

**Comment by mihail-minkov** [comment]
Thanks a lot @verlok a couple of coffees headed your way :)
