### ISSUE TITLE
Does LL has .load() method now?

### ISSUE THREAD

**Issue by galina-from-belarus** [verlok/vanilla-lazyload#471]
I've tried forced loading of images, but I got only errors. Then I get methods from LazyLoad Instance. There was no .load(), only .loadAll(). Is .load() methos available now?

**Comment by verlok** [comment]
Yes it is, but it's static now. So you need to do `LazyLoad.load(element, settings)` instead of calling it on your object instance. 

Take a look at the documentation for more information, or at the load demo.
