### ISSUE TITLE
any failover solution for image?

### ISSUE THREAD

**Issue by hn24** [verlok/vanilla-lazyload#478]
Hi all,
I have two domain to place my images: **maindomain.com/images/001.jpg** and **backupdomain.com/images/001.jpg**
Just want to display the image 001 from the first url by default, how can i load the second url if the web browser cannot load the image from the first url (may be 404 or 505 or time our)?

**Comment by verlok** [comment]
Hey @hn24,
thank you for asking this. 

You could use the `callback_error` option, which is called whenever an image throws an error while loading. In that callback function, you can replace the domain in your  `data` attributes and force the loading once again using the `LazyLoad.load(element)` static function. 

Let me know how this works for you!

**Comment by hn24** [comment]
thanks @verlok , it works for me!

**Comment by verlok** [comment]
Hey @hn24, 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 
Have a nice day!
