### ISSUE TITLE
Missing types in interface ILazyLoadOptions

### ISSUE THREAD

**Issue by that-bman** [verlok/vanilla-lazyload#480]
**Describe the bug**
The typings need updating with the missing types:
- data_bg_hidpi
- data_bg_multi
- data_bg_multi_hidpi
- data_poster
- class_applied
- unobserve_completed
- unobserve_entered
- cancel_on_exit
- callback_applied
- callback_cancel

[https://github.com/verlok/vanilla-lazyload/blob/master/typings/lazyload.d.ts](https://github.com/verlok/vanilla-lazyload/blob/master/typings/lazyload.d.ts)

**LazyLoad version**

- Version 17.1.2

**Comment by ar53n** [comment]
#482

**Comment by erichstark** [comment]
Thats great! I was considering to work on it 👍

**Comment by verlok** [comment]
Merged #482. Releasing a new version. Thank you all!
