### ISSUE TITLE
当dom结构嵌套的层级大于8的时候不能加载图片

### ISSUE THREAD

**Issue by brandyjin** [verlok/vanilla-lazyload#481]
问题：当dom结构嵌套的层级大于8的时候不能加载图片。

**Comment by verlok** [comment]
Hey @brandyjin ,
thanks for reporting. 

I'm not a native English speaker but I write everything in English on GitHub. Would you be so kind to to the same? Thanks

**Comment by verlok** [comment]
Closing this for now, feel free to reopen (in English) if you still need help.

**Comment by brandyjin** [comment]
> Hey @brandyjin ,
> thanks for reporting.
> 
> I'm not a native English speaker either, but I write everything in English on GitHub.
> Would you be so kind to to the same?
> 
> That would be very appreciated.
> Thanks

I'm sorry. Thanks for reminding.
