### ISSUE TITLE
Lazyloading Youtube Iframe Causes Back Button Issue in Firefox

### ISSUE THREAD

**Issue by nickreese** [verlok/vanilla-lazyload#483]
**Describe the bug**
Lazyloading Youtube Iframe Causes Back Button Issue in Firefox. Basically the iframe loads, then when you hit back, the iframe disappears.

**To Reproduce**

`<iframe width="730" height="411" data-src="https://www.youtube-nocookie.com/embed/WTJwh6dO8Qo?modestbranding=1&showinfo=0&rel=0&cc_load_policy=1" class="lazy youtube" frameborder="0" allowfullscreen></iframe>`

**Expected behavior**
Iframe lazyloads but doesn't hijack the back button. 

**LazyLoad version**
Please report which version of LazyLoad you're using.

17.1.2

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 80

**Comment by verlok** [comment]
Hey @nickreese 
thanks for reporting. 

This seems to me a browser bug, not a library bug. What could I do in LazyLoad do to solve this issue?

**Comment by verlok** [comment]
@nickreese I'm closing this, feel free to reopen if you still need help.
