### ISSUE TITLE
Main browser window and scrolling panels

### ISSUE THREAD

**Issue by DavidVonAmri** [verlok/vanilla-lazyload#485]
**Is your support request related to a problem? Please describe.**
When trying to use lazyload with one instance of main body together with two instances of scrolling panels (horizontal) the horizontal scrolling panel won't lazyload as expected.

**To Reproduce**
1. Add a global lazyload instance (browser window) and multiple lazyload instances for scrolling panels (horizontal).
2. Scroll the panels, images will get lazyloaded but when getting out of view again loose the loaded status and will not load again.

**Expected behavior**
Once scrolled to the right or left, images would get lazyloaded and keep the loaded status.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version: 17.1.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4183.102 (Officiell version) (64 bitar)

**Screenshots**
![captured](https://user-images.githubusercontent.com/18591828/93176594-c93e8f80-f731-11ea-9010-43bb4510dadf.gif)

**Additional context**
Markup as follows:

```
    var test1 = new LazyLoad({
        threshold: 0,
        container: document.getElementById("scroll_panel_1")
    });

    var test2 = new LazyLoad({
        threshold: 0,
        container: document.getElementById("scroll_panel_2")
    });

    var bodyLazy = new LazyLoad({
        threshold: 350
    });
```

**Comment by DavidVonAmri** [comment]
Okey, so I think I've found a "solution". I had to load the scrolling panels according to the documentation like this:

```
    var lazyLoadInstances = [];

    var initOneLazyLoad = function (horizContainerElement) {
        // When the .horizContainer element enters the viewport,
        // instantiate a new LazyLoad on the horizContainerElement
        var oneLL = new LazyLoad({
            container: horizContainerElement
        });
        // Optionally push it in the lazyLoadInstances
        // array to keep track of the instances
        lazyLoadInstances.push(oneLL);
    };

    // Load horizontal lazyload
    var lazyLazy = new LazyLoad({
        elements_selector: ".hqy-horizontal .hqy-lazy",
        threshold: 0,
        callback_enter: initOneLazyLoad,
        unobserve_entered: true
    });
    
    // And then load the main window lazyload
    var bdyLazy = new LazyLoad({
        threshold: 1350,
        elements_selector: ".hqy-lazy"
    });
```

**Comment by verlok** [comment]
Hey @DavidVonAmri ,
thanks for reporting and for the patience, I'm replying very late.

Yes, that's exactly the solution I was about to propose: having different instances of lazyload on different containers and elements, to avoid collision.
