### ISSUE TITLE
How to use it in server side react?

### ISSUE THREAD

**Issue by rockse** [verlok/vanilla-lazyload#487]
Hi, I had to like use `vanilla-lazyload` in server-side react (in `next.js`)

I went through https://codesandbox.io/s/20306yk96p. It does work for client-side react but for server-side `document` is not declared as it's only available ion browser instance not on the server. How to resolve that issue, thanks?

**Comment by verlok** [comment]
Hey @rockse ,
sorry that I'm late.

Did you find a solution then?

**Comment by verlok** [comment]
I'm going to close this. Feel free to reopen if you still need help.

**Comment by Ir1d** [comment]
Hi @verlok @rockse, were you successful using this in server side react?

**Comment by xiaomuzizier** [comment]
Did you find a solution later?
