### ISSUE TITLE
Upgrading from 8.16 to 17.1.2

### ISSUE THREAD

**Issue by briwg** [verlok/vanilla-lazyload#488]
Hi,

I have two questions about upgrading from 8.16 to 17.1.2:

1) In 8.16 if I used the function below all images in the page with a data-src would lazy load.  In 17.1.2 it appears the  class="lazy" has to be added. Is this correct?

(function () {
                new LazyLoad({
                    threshold: 400
                });
 }());

2) By default does LazyLoad only apply to images? I want to ensure that it does NOT try to lazy load iFrames, background videos and scripts etc.

Thanks

Brian

**Comment by verlok** [comment]
Hey @briwg ,
sorry for replying late.

1. Yes, you need to apply the `class="lazy"` to the elements you want to lazyload.
2. It applies to every element with the `lazy` class, so just add it to the images and NOT to iframes.

Let me know if you still need help.
Thanks
