### ISSUE TITLE
Does vanilla-lazyload work with jQuery and getJSON()? 

### ISSUE THREAD

**Issue by jg-digital-media** [verlok/vanilla-lazyload#489]
**Is your support request related to a problem? Please describe.**
Good Day.

I'm trying to add some lazyloading to a number of projects I'm working on. Here are a couple or examples.

## https://projects.jonniegrieve.co.uk/php_website/
On this project, it works as expected with PHP.  This project has LazyLoading set up and functioning the way I would expect it. The data-src attributes are loaded directly from LazyLoad.js. Which is verified in the Network tab of ChromeDevTools.

### markup returned in Chrome DevTools showing lazyloading in effect.
    <li>
        <img data-src="img/drama/hacksaw.jpg" class="media-img lazy loaded" title="Hacksaw Ridge (2011)" src="img/drama/hacksaw.jpg" data-was-processed="true">
        <a href="#" class="sub-content-title">Hacksaw Ridge (2009)</a>
    </li>

### Lazyloading

    //lazyloading
    var lazyLoadInstance = new LazyLoad({
        elements_selector: ".lazy",
        // ... more custom settings?
        //threshold: 1472,
    });

## https://jonniegrieve.co.uk/assets/project_status_images/index.html 
It works in a similar way on this page. 

I'm using JavaScript to loop through and retrieve the image data using JSON and jQuery's ```getJSON()``` method.

### app.js
    jQuery.getJSON('data/project-list.json', function(photoData) {
        
        let itemAll = photoData.projects.length;
        console.log(photoData.projects.length);
        
        //display data count to browser
        project_count.textContent = "( " +  photoData.projects.length  + " )";
    
    
        for (let i=0; i < itemAll; i++) {
            
            jQuery(`
                <li>
                    <a href="${photoData.projects[i].project_url}" target="blank">
                       <img src="${photoData.projects[i].img_url}" class="site-images lazy" alt="${photoData.projects[i].project_alt}" title="${photoData.projects[i].project_alt}" tabindex="" />
                       
                    </a>
    
                    <div class="project_info">
                        <div class="${photoData.projects[i].project_status }"></div>
                        <div class="project_name">${photoData.projects[i].project_name }</div>
                    </div>
               </li>`).appendTo('.project-status-data');     
        }   
    });

### JSON data

    {
        "projects": [
            {
                "project_name": "Value",
                "project_url": "value 2",
                "img_url": "value 3",
                "feat_img_url": "value 4",
                "project_alt": "value 5",
                "project_type": "value 6",
                "project_status": "value 7",
                "status": true,
                "img_type": "src",
                "img_type_data": "data-src"
            }, {
                "project_name": "Value",
                "project_url": "value 2",
                "img_url": "value 3",
                "feat_img_url": "value 4",
                "project_alt": "value 5",
                "project_type": "value 6",
                "project_status": "value 7",
                "status": true,
                "img_type": "src",
                "img_type_data": "data-src"
            }, {
            //more data
            }
         ]
    }

### html

    <li>
       <a href="https://projects.jonniegrieve.co.uk/ajax_project" target="blank">
          <img src="https://projects.jonniegrieve.co.uk/assets/img/list/ajax_project.png" class="site-images lazy" alt="Go to Ajax Project Website" title="Go to Ajax Project Website" tabindex="">
      </a>
    
      <div class="project_info">
         <div class="complete"></div>
         <div class="project_name">Ajax Project</div>
      </div>
    </li>

### implement lazyloading in app.js

       var lazyLoadInstance = new LazyLoad({
            elements_selector: ".lazy",
            // ... more custom settings?
            //threshold: 1472,
        });

There are no console/JavaScript errors returned into the console. Is there something inherent about lazyloading that it doesn't work when the markup is injected into the DOM dynamically?  Can lazyloading work with jQjuery and JSON or do I need to change tactic?

**To Reproduce**
1. Go to 'https://projects.jonniegrieve.co.uk/php_website/'and 'https://jonniegrieve.co.uk/assets/project_status_images/index.html '
2. Click on 'ChromeDevTools' or your Browsers DevTools to test images are being reported as lazyloaded
3. Scroll down to test lazyloading
4. No Console errors to report.

**Expected behavior**
Expecting to see images replaced via the data-src attribute for loading. However, even though the data is compiled via JavaScript looping and retrieving JSON data with getJSON()method with jQuery and there are no console errors it is not working. Is there a known reason why this is?

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version [3.5.1]

**Screenshots**

**Additional context**

**Comment by verlok** [comment]
Hey @jg-digital-media ,
I can see you're using a very old version of lazyload, please update to the latest which is 17.1.3

The websites you linked are working as expected, so it seems you've already solved the problem.

Find more info about loading dynamic content and lazy loading the images in the [readme, dynamic content section](https://github.com/verlok/vanilla-lazyload#dynamic-content).

Let me know if you still need help.
Thanks

**Comment by jg-digital-media** [comment]
Thank you Andrea,

I appreciate your guidance and hope I haven't wasted too much of your time.  

It does seem I was using a previous version of lazyload.  I was labouring under the belief had the latest one, somehow.

So there's no difference between the initiator on DevTools showing up as jQuery or lazyload? But encouraging to know the second project is working as far as you're concerned.  Thanks, will be in touch if I need further follow up on this.

**Comment by verlok** [comment]
Hey @jg-digital-media, 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 
Have a nice day!
