### ISSUE TITLE
Seeing alt labels with empty image icon before load

### ISSUE THREAD

**Issue by paulhuisman** [verlok/vanilla-lazyload#493]
**Describe the bug**
The one or two second before my image is being lazy loaded i see an empty image tag with the alt label.

How can i prevent this?

**Expected behavior**
Do not show anything untill the image is loaded, then show the image.

**LazyLoad version**
Latest version (17.1.0)

**Desktop (please complete the following information):**
 - OS: Mac osx
 - Browser: Chrome 
 - Version: 86

**Screenshots**
![image](https://user-images.githubusercontent.com/37524/98528063-134c7900-227c-11eb-910a-529f1b6884d2.png)

**Comment by verlok** [comment]
Hey @paulhuisman,

you can solve it with CSS hiding the images without a `src` attribute set. 

You can copy the CSS from any of the demos in the demos folder.

**Comment by verlok** [comment]
For example the following

```css
img:not([src]):not([srcset]) {
  visibility: hidden;
}
```

Let me know if this solved your issue

**Comment by verlok** [comment]
I've also added it to the README file, Recipes section.

**Comment by verlok** [comment]
@paulhuisman did you solve?

**Comment by paulhuisman** [comment]
Yes thank you!

**Comment by verlok** [comment]
Hey @paulhuisman,
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 

Have a nice day!
