### ISSUE TITLE
Avoid content reflow benchmark link is broken

### ISSUE THREAD

**Issue by bridgeport** [verlok/vanilla-lazyload#495]
Hi. Thanks for this great scripts. On your readme, the following section:

> There are many ways to avoid content reflow. I've **tested three of them** and found that the fastest is to avoid using a placeholder at all, and use the vertical padding trick.

The "tested three of them" link leads to a 404 not found page. I was interested in reading about your benchmark.

Thanks.

**Comment by verlok** [comment]
Thanks @bridgeport,
I've fixed that link now. 

It now points to [this repo](https://github.com/verlok/lazyload_placeholders_test). 
I hope you find the information you want there!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.
Thank you for thinking about it. 

Have a nice day!
