### ISSUE TITLE
Images requesting multiple times on Safari ver 14.0.2

### ISSUE THREAD

**Issue by danielLee0721** [verlok/vanilla-lazyload#500]
First of all - amazing script! This must have been a lot of work creating it and now maintaining it!!

**Describe the bug**
I just tried the following example https://www.andreaverlicchi.eu/vanilla-lazyload/demos/background_images.html on macOS Big Sur Safari ver 14.0.2, and it seems to be loading duplicates of every img.

**To Reproduce**
Use the following example on safari browser 14.0.2
https://www.andreaverlicchi.eu/vanilla-lazyload/demos/background_images.html 

**LazyLoad version**
I am using vanilla-lazyload ver 17.3.0.

**Desktop (please complete the following information):**
OS: macOS Big Sur
Browser: Safari 14.0.2

**Additional context**
Please find attached screenshot.

I may be interpreting it wrong though. Any help would be greatly appreciated.

Thank you!
![safari](https://user-images.githubusercontent.com/76029842/105096383-f8189980-5a74-11eb-9385-8ccd667f9175.png)

**Comment by Yinci** [comment]
I have a similar issue. In my case, an image is not available (moved or deleted), after which the images fails to load, but then retries anyway. This causes a lot of network traffic, even though it obviously can't load. 

Also running 17.3.0, with macOS Catalina (10.15.5), Safari 13.1.1

**Comment by zapatoche** [comment]
I had a similar issue and it was driving me crazy until a colleague pointed to me that caching was disabled when the dev tools are open. Maybe it's a similar issue 🤞. I'm much 😃now.

**Comment by danielLee0721** [comment]
> I had a similar issue and it was driving me crazy until a colleague pointed to me that caching was disabled when the dev tools are open. Maybe it's a similar issue 🤞. I'm much 😃now.

Thanks for the suggestion! I will give it a try!

**Comment by verlok** [comment]
Hi @danielLee0721,
I assume you'll have solved your issue by now.

Let me close this. 
Feel free to reopen if you still need help.
