### ISSUE TITLE
Q about duplicate initiator in network tab for lazy loading background images

### ISSUE THREAD

**Issue by danielLee0721** [verlok/vanilla-lazyload#501]
**Is your support request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I am trying to lazy load background images - and everything seems to be working fine but I am getting duplicate requests - one by (index) and another by the lazyload script.

**LazyLoad version**
Version 17.3.0

**Desktop (please complete the following information):**
OS: macOS Big Sur Ver 11.1
Chrome: Ver 87.0.4280.141

**Screenshots**
Please find attached.
![Screen Shot 2021-01-19 at 5 03 50 PM](https://user-images.githubusercontent.com/76029842/105098937-d4575280-5a78-11eb-9bfa-c7e4a4076a38.png)
![Screen Shot 2021-01-19 at 5 03 57 PM](https://user-images.githubusercontent.com/76029842/105098934-d3bebc00-5a78-11eb-9413-9a18f69261c6.png)

**Additional context**
Is this normal behaviour? Please forgive me if it is...

Thank you!

**Comment by verlok** [comment]
Hey @danielLee0721,
I'm sorry I must have missed this issue.

I assume you'll have solved by now.
Let me close this. 

Feel free to reopen if you still need help.

**Comment by crilleengvall** [comment]
I just ecountered the same problem, and this answer by @zapatoche helped: https://github.com/verlok/vanilla-lazyload/issues/500#issuecomment-772807425
