### ISSUE TITLE
video data-src mobile webm

### ISSUE THREAD

**Issue by zdlldz** [verlok/vanilla-lazyload#504]
Greetings -- Adding here for a potential future friend: 

In retrospect it's obvious/makes sense, but was having issues tracking down why lazy video was not working on ios: we are a webm first (+ mp4 fallback) shop, and were using the webm in the video's element's data-src. Needs to be mp4. Duh 😎

Thanks for the great plugin + legwork @verlok!! 🙏

**Comment by verlok** [comment]
Hey @zdlldz,
sorry for the late reply.

I'm not sure I understood what you're asking / suggesting here.

I'm afraid this script doesn't have anything to do with the format of the videos you choose to use (WebP or MP4) since it doesn't make any logic on it.

What am I missing?

**Comment by verlok** [comment]
Hey @zdlldz, 
I didn't receive any further reply so I'm going to assume you "solved" some how, and I'm closing this.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
