### ISSUE TITLE
Horizontal scrolling panel (marquee) with css horizontal transform animation

### ISSUE THREAD

**Issue by lea37** [verlok/vanilla-lazyload#506]
Hello and thank you for this great lazyload package.
I was wondering if there is a way to update the lazyload instance for automatic css scrolling from css animation ? 

I have a fake "marquee" html element such as
```
<div class="hContainer">
 <img alt="A lazy image" class="lazy" data-src="lazy.jpg" />
 <img alt="A lazy image" class="lazy" data-src="lazy.jpg" />
 <img alt="A lazy image" class="lazy" data-src="lazy.jpg" />
 <img alt="A lazy image" class="lazy" data-src="lazy.jpg" />
</div>
```

This element has a transform translateX infinite animation to make it look like an automatic slider. 

Is there a way to update the lazyload each time a new image enter viewport until there is no more image to load ?
Thank you for your help

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version ^17.3.0

**Desktop (please complete the following information):**
 - OS: Mac OS BigSur 11.1
 - Browser Chrome
 - Version 88.0

**Comment by marioloncarek** [comment]
@lea37 any luck with this?

**Comment by lea37** [comment]
> @lea37 any luck with this?

Wouah! That's old 😅 there is now native lazyload for images and intersection observer. Much easier to deal with this kind of things today!

**Comment by marioloncarek** [comment]
@lea37 yea it was a long shot :D saw you closing the issue so i was hoping that you found a solution. i still love using this lib for some other reasons but its still a option to convert to native for this section. thanks anyway!
