### ISSUE TITLE
Video autoplay not working on iOS Safari and Chrome

### ISSUE THREAD

**Issue by epignosis567** [verlok/vanilla-lazyload#511]
My video is either not lazy loading or not auto playing on Safari and Chrome iOS when setting the data-src as anything other than streaming directly from my server. I typically use dropbox to stream my mp4 videos since my go daddy hosting is slow. I'm able to get autoplay to work when the video is on my server but not when it's a link. Everything seems to work properly on desktop but I only see the poster on iOS.
Here is my file on github: 
https://github.com/epignosis567/mygithub/tree/main/lazyLoadBootstrap

**Comment by verlok** [comment]
Hey @epignosis567 , thanks for reporting this.
What happens if you load those videos not using lazyload, so just using `src` instead of `data-src`?
Does the autoplay work correctly in that case?

**Comment by verlok** [comment]
Hey @epignosis567 ,
I'm closing this for now since you didn't reply.
Feel free to reopen if you still need help.
