### ISSUE TITLE
lazy loaded video element preloads whole video in Safari

### ISSUE THREAD

**Issue by hasan-wajahat** [verlok/vanilla-lazyload#512]
In our codebase we use the awesome lazyload library's `callback_enter` function to perform some customization on our videos. Because of which our selector contains `video` element as well.

Now all this works fine for browsers like Chrome but in Safari because of the code 
```js
element.load();
```
in the function `setSourcesVideo` in `lazyload.setSources.js` causes the video to preload completely even if `preload="none"` is set on the video element.

I believe element should respect the preload status of video and only load if preload is not set as "none" or "metadata".

**To Reproduce**
Create a video element in safari and lazy load it. Video element can be like so:

```html
<video  preload="none" class="lazy" controls controlslist="nodownload">
  <source src="video_url" type="video/mp4">
</video>
```

In Safari this will start download thing whole on page load even before play is clicked.

**Expected behavior**
When preload="none" is set then video should not download in entirety before play is pressed.

I have on purpose not created a bug report because I know this has partly do with how browsers are loading video and Safari actually downloads the whole video instead of loading chunks. But would love to know if something can be done for this.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.1.3

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser Safari
 - Version 14.0

**Comment by verlok** [comment]
Hey @hasan-wajahat,
sorry I must have missed this issue back in March.

I assume you'll have solved this issue by now.

Let me close this issue,
but feel free to reopen it if you still need help.

Thanks, 
and sorry again.

**Comment by hasan-wajahat** [comment]
Hey @verlok no problem about the delay.
So the issue was not actually resolved and I ended up not using the library to lazy load videos. In fact I had to use my own intersection observer.
I would recommend that you still take a look at this issue as it is worth fixing.

**Comment by verlok** [comment]
Thanks @hasan-wajahat,
reopening and digging into it now.

**Comment by verlok** [comment]
Hi again,

I've investigated by splitting the video demo, which had autoplay, in 2 demos.

The demo page without the autoplay is always called `video.html` and you can [try it live here](https://www.andreaverlicchi.eu/vanilla-lazyload/demos/video.html).

The demo page contains 3 videos, with their attributes set to:

1. `preload="none"`
2. `preload="metadata"`
3. `preload="auto"`

And yes, I've verified that Safari starts loading the whole video even on the one with `preload=none`.

This is specifically true only for Safari, so you're right about the sentence you wrote above:

> I know this has partly do with how browsers are loading video and Safari actually downloads the whole video instead of loading chunks.

But then you added:

> But would love to know if something can be done for this.

Are you suggesting that this LazyLoad library should consider the `preload` attribute, and when it's set to `"none"` and the `autoplay` is also missing, it should avoid copying the `data-src` attributes into `src` of the `<video>` elements, only on Safari?

**Comment by verlok** [comment]
Thing is, if you read the [specification of the `preload` attribute on the `<video>` tag on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#attr-preload), there's a note that states:

> The specification does not force the browser to follow the value of this attribute; it is a mere hint.

So, my intention is to leave it like that, instead of forcing Safari to do something different, since Safari's behaviour is aligned with the specifications: it is actually allowed to ignore the value of `preload` attribute.

More generically, I think the main focus of this library should be around the copy of the `data-src` attributes to the `src` attributes, with the given `options` object as the unique divergence in its behaviour, instead of managing differences between browsers, additional statuses for the elements, and ultimately managing more complexity via adding more code.

What do you think?

**Comment by verlok** [comment]
Hey @hasan-wajahat, 
I’m going to assume you solved, so I'm closing this now.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!

**Comment by hasan-wajahat** [comment]
Thanks @verlok, I understand your reasoning there.
Anyways as a thank you I bought a cup of coffee, hope it keeps you motivated to do your awesome work!

**Comment by verlok** [comment]
Thanks @hasan-wajahat, you rock 🤟🏼

**Comment by Izofeu** [comment]
Hey,
adding to the report that now even Chromium browsers preload videos in this circumstance. Though it's only the metadata that gets preloaded, it's still annoying nonetheless as it adds unnecessary traffic to a webserver. I've hosted the library myself, simply removing the 2 element load lines and now it works like I want it to. Thank you @verlok for continuous maintaining of this great js library!

**Comment by verlok** [comment]
Hey @Izofeu, 
thank you for the update and the trick. I'm glad you were able to customise it and make it work like you wanted. 

If you’re happy with my support, the documentation and the effort I’ve been putting on this library in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
