### ISSUE TITLE
16.1.0 update to 17.3.1: dynamic data-bg src beeing ignored in react

### ISSUE THREAD

**Issue by Xairoo** [verlok/vanilla-lazyload#513]
The update to 17.3.1 from 16.1.0 needs a change on my code for my dynamic `data-bg` src. The new version ignores my `data-bg` changes. Maybe related to enhancement https://github.com/verlok/vanilla-lazyload/issues/446.

This works with 16.1.0:

```jsx
render() {
	const { thumb } = this.props.asset;
	return <div className="asset-cover" data-bg={thumb ? thumb : ''} />;
}
```

17.3.1:

```jsx
render() {
	const { thumb } = this.props.asset;
	if (thumb) {
		return <div className="asset-cover" data-bg={thumb} />;
	} else {
		return null;
		return <div className="asset-cover" />; // This does not work, also data-bg={null} doesn't work
	}
}
```

I can use the 16.1.0 code with 17.3.1 if I call document.lazyLoadAssetCover.loadAll(); after every update(), but yeah... :)

```jsx
if (!document.lazyLoadAssetCover) {
	document.lazyLoadAssetCover = new LazyLoad({
		elements_selector: '.asset-cover',
	});
}

export class LazyBgImage extends React.Component {
	shouldComponentUpdate(nextProps) {
		document.lazyLoadAssetCover.update();
		// document.lazyLoadAssetCover.loadAll();
		return true;
	}

	componentDidMount() {
		document.lazyLoadAssetCover.update();
		// document.lazyLoadAssetCover.loadAll();
	}

	componentDidUpdate() {
		document.lazyLoadAssetCover.update();
		// document.lazyLoadAssetCover.loadAll();
	}

	render() {
		const { thumb } = this.props.asset;
		return <div className="asset-cover" data-bg={thumb ? thumb : ''} />;
	}
}
```

Any ideas? I mean it works, but why did it break?

**Comment by verlok** [comment]
I agree that you shouldn’t call the `loadAll` method after every `update`. 

One thing that changed from 16 to 17 is the default value of the `cancel_on_exit` option (now defaulting to `true`). Would you be able to set it to `false` and see if it solves you issue?

**Comment by Xairoo** [comment]
`cancel_on_exit: false` didn't fixed it.

Also tried changing the src via interval, nothing will happen. Something has changed since v16 =)
Anyway, still a really great piece of code!

Sample repo for reproduction: https://github.com/Xairoo/demo-lazyload
If you are checking this... In App.js, line 12, `setSrc(false);` did the dirty trick, just remove it.

Functional components a great to read (perhaps for your examples - but the problem should be fixed):
```
import React, { useEffect } from 'react';
import LazyLoad from 'vanilla-lazyload';

const callback_loaded = function (e) {
	console.log('callback_loaded', e);
};
const callback_loading = function (e) {
	console.log('callback_loading', e);
};

// Only initialize it one time for the entire application
if (!document.lazyLoadAssetCover) {
	document.lazyLoadAssetCover = new LazyLoad({
		elements_selector: '.cover',
		callback_loading: callback_loading,
		callback_loaded: callback_loaded,
	});
}

const LazyBgImage = (props) => {
	useEffect(() => {
		document.lazyLoadAssetCover.update();
	}, [props.src]);

	if (props.src) {
		return <div className="asset-cover" data-bg={props.src} />;
	} else {
		return null;
	}
};

export default LazyBgImage;
```

**Comment by verlok** [comment]
Hey @Xairoo,
sorry for forgetting to reply to this issue.

Do you still need help on this?

**Comment by verlok** [comment]
Closing this for now, let me know if you still need assistance.
