### ISSUE TITLE
lazy load is not working properly

### ISSUE THREAD

**Issue by ashehzadgec** [verlok/vanilla-lazyload#514]
**Is your support request related to a problem? Please describe.**
A clear and concise description of what the problem is.
The problem is that if I do mention container in options, lazy does not work at all. And If I go with the default container then after new Dom when I call for lazy update function it throws me an error as attached. I am using locomotive smooth scroll with AJAX and selecting the locomotive scroll container itself or it's child container for lazy.update(), it does not work in either situation. I am using parcel bundler for the project so I am attaching some pics for your reference. Any guidance in this regard will be highly appreciated.
**To Reproduce**

**Expected behavior**

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Screenshots**
![error with specifying container](https://user-images.githubusercontent.com/65112198/111784303-1962fe00-88dd-11eb-97e6-bf94788e5d41.png)
![error-without-custom container](https://user-images.githubusercontent.com/65112198/111784431-35669f80-88dd-11eb-9a4e-74e97cc929eb.png)
![lazy destroy](https://user-images.githubusercontent.com/65112198/111784446-3992bd00-88dd-11eb-958d-ad7fa0a25337.png)
![lazy js](https://user-images.githubusercontent.com/65112198/111784454-3bf51700-88dd-11eb-9fb4-9ff52d24ad36.png)
![lazy update](https://user-images.githubusercontent.com/65112198/111784462-3f889e00-88dd-11eb-9154-a2a5bc0ccd92.png)
**Additional context**
I tried different methods to get it working bu always throws the same errors after new Dom. I must be missing something but could not figure out what it is.

**Comment by verlok** [comment]
Hey @ashehzadgec,
sorry I must have missed this issue back in March.

I assume you'll have solved this issue by now.

Let me close this issue,
but feel free to reopen it if you still need help.

Thanks, 
and sorry again.
