### ISSUE TITLE
Infinite scrolling for paginated product divs

### ISSUE THREAD

**Issue by maxibwoy** [verlok/vanilla-lazyload#516]
Hi, is it possible to implement it on a set of div’s (containing product title, price, image) that have pagination (with a “see more products” button) to achieve infinite scrolling?

My code is the following

```
<section class="bg-dark text-white pt-2 overflow-hidden">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="row gutter-2 gutter-lg-3">
                    
                    <!-- prodotto singolo -->
                    <div class="col-12 col-sm-6 col-lg-4">
                        <div class="product">
                            <figure class="product-image">
                                <a href="#">
                                    <img src="image.jpg">
                                </a>
                            </figure>
                        </div>
                        <div class="product-meta">
                            <h3 class="product-title"><a href="#">Titolo prodotto</a></h3>
                            <div class="product-price">
                              <span>100 €</span>
                              <span class="product-action">
                                <a href="#">Scopri di più</a>
                              </span>
                            </div>
                          </div>
                    </div>

                    <!-- altri prodotti ripetuti-->

                    <!-- pagination -->
                    <a href="{auto_path}" class="col-12 text-center">Mostra più prodotti</a>

                </div>
            </div>
        </div>
    </div>
</section>
```

Thanks very much!

**Comment by verlok** [comment]
Hey Max,
thank you for opening this. 

It is indeed possible. The key is calling the `update()` method after the new content has been added to the page. 

There’s a demo on how to do that. 
https://github.com/verlok/vanilla-lazyload#-demos

Find the demo in the table with the description “Adding dynamic content, then `update()` LazyLoad”. 

From there you will have access to the exact code to use and the live demo. 

Let me know if this helps!

**Comment by maxibwoy** [comment]
That’s great, thank you! How do you get the add content button to be triggered automatically when, say, 50% of the container is in the viewport? 

That way we have full infinite scrolling, for example like here: https://mobile.yoox.com/uk/women/shoponline

**Comment by verlok** [comment]
You get that by calling the `update()` method after the new products have been injected in the page.

I'm closing this for now. Let me know if you still need help.
