### ISSUE TITLE
For compressed HTML, vanilla-lazyload lazy-loaded the script tag, resulting in an error 

### ISSUE THREAD

**Issue by wayne0926** [verlok/vanilla-lazyload#518]
**Describe the bug**
For compressed HTML, vanilla-lazyload lazy-loaded the script tag, resulting in an error 

**To Reproduce**
1. Compress HTML
2. View the source code
3. The console reports an error: "Uncaught ReferenceError: Pjax is not defined
"

**Expected behavior**
The script tag should be recognized under certain circumstances 

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version [e.g. 8.x.x, 10.x.x, 11.x.x]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Screenshots**
![image](https://user-images.githubusercontent.com/63389859/113476791-5835ae00-94b0-11eb-82fc-41be8c6b72a0.png)

**Additional context**

**Comment by verlok** [comment]
I’m sorry @wayne0926, but I fail to understand why compressed HTML should have anything to do with this script.

**Comment by wayne0926** [comment]
> I’m sorry @wayne0926, but I fail to understand why compressed HTML should have anything to do with this script.

Hmm... When the HTML is not compressed, this lazy-loaded code will not appear

**Comment by verlok** [comment]
Again, this doesn’t seem to have anything to do with this script. I sense this might have something to do with the way you compress HTML code. Could it be?

**Comment by wayne0926** [comment]
> Again, this doesn’t seem to have anything to do with this script. I sense this might have something to do with the way you compress HTML code. Could it be?

It may indeed be, I will test it later, because it is true that the problem only occurs after compression
