### ISSUE TITLE
Image elements do not have explicit width and height

### ISSUE THREAD

**Issue by briwg** [verlok/vanilla-lazyload#519]
Hi,

Lighthouse in Chrome and Page Speed Insights flag up images which don't explicitly have width and height values set.  I believe this will soon become more of an issue with Google using Core Web Vitals as a ranking signal from May 2021.  

In the examples provided in the Getting Started section the height and width values do not appear to be set. Can you provide some guidance on best practice? 

Thanks

Brian

**Comment by verlok** [comment]
Hey @briwg thanks for the question. 

I didn’t specify any width or height in the examples to avoid distractions from the attributes that are required to the script. 

Of course it’s a best practice to specify width and height to the images, but there are also other ways to make the browser reserve space for the images before they load and avoid Cumulative Layout Shift. 

I believe I documented some ways to reserve space in the README. 

Did that answer your question?

**Comment by verlok** [comment]
See https://github.com/verlok/vanilla-lazyload#-tips--tricks

You’re right I didn’t mention applying width and height attributes to the images directly, will do.

**Comment by verlok** [comment]
@briwg what do you think if I used the info I’ve considered in this blog post, or a link to it?

https://www.andreaverlicchi.eu/aspect-ratio-modern-reserve-space-lazy-images-async-content-responsive-design/

**Comment by briwg** [comment]
Hi,

That's an interesting post. I've not had a chance to look into aspect-ratio
and Safari support is important for me. At the moment I expect I'll stick
with the vertical padding trick.

Thanks

Brian

**Comment by verlok** [comment]
Hey @briwg , 
I’m glad I solved your issue. 

Please consider using mapped `aspect-ratio` in the future, which is already supported in Safari 14 today. 

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 
Have a nice day!
