### ISSUE TITLE
Can’t get `callback_finish` to fire

### ISSUE THREAD

**Issue by jasewarner** [verlok/vanilla-lazyload#523]
My LazyLoad instance is working fine with the exception of the `callback_finish` function.

Here’s the snippet I'm playing around with:

```js 
const loaded = () => {
    console.log(`Finished`);
}

if (typeof LazyLoad !== 'undefined') {

    const lazyLoadInstance = new LazyLoad({
        callback_finish: loaded
    });

}
```

Am I missing something obvious with regards to the `callback_finish` function?

Thanks

**Comment by verlok** [comment]
Hey @jasewarner ,
thank you for your question. 

That callback is called when all the images in the page are loaded. 

How many images you have on the page? When do you expect that callback to be called?

Have you checked the demos in the demos folder? All of them have callbacks called, is it what you expect?

Thanks for your patience. 
verlok

**Comment by jasewarner** [comment]
@verlok , thanks for your speedy reply!

Yep, I understand that `callback_finish` should fire when all images have loaded.
For the moment, I'm just testing with 5 images (all of which lazy load as expected).

I have indeed used the demos as a point of reference. 

Nothing is logged to the console when using the callback function, as per the snippet I provided in my initial comment.

Any thoughts?

**Comment by verlok** [comment]
Hey @jasewarner ,
to answer your question, I would also need to see your HTML code for all the 5 images. 
Would you be able to share it here?
Or maybe you could create a working version of your code on Codepen.io or Codesandbox?
Thanks

**Comment by jasewarner** [comment]
@verlok , thanks for the reply. Here's the markup that I'm using for each image (using actual images in the real snippet, so obviously the paths are different, but rest assured they all work):

```
<figure class="mb-0">
    <picture>
        <source class="lazy" data-srcset="image.jpg 1x, image.jpg 2x" media="(min-width: 992px)">
        <source class="lazy" data-srcset="image.jpg 1x, image.jpg 2x" media="(min-width: 768px)">
        <source class="lazy" data-srcset="image.jpg 1x, image.jpg 2x" media="(min-width: 576px)">
        <img class="lazy img-fluid w-100" alt="" src="placeholder.svg" data-src="image.jpg" data-srcset="image.jpg 1x, image.jpg 2x">
    </picture>
</figure>
```

The actual lazy loading is working absolutely fine – no problems there.
It's literally just the `callback_function` that isn't firing.

**Comment by verlok** [comment]
Aaaah, I think I see the problem there!

You added the `lazy` class on each `source` tag, so the script considers and counts them as lazy elements to load. 

Try adding the `lazy` class only on the `img` tag, like stated in the documentation. 

And please tell me if it worked. It should!

**Comment by jasewarner** [comment]
Oh! I’m such a Rodney Plonker – totally missed that. In my defence, I was working on this in the evening after a long day’s work… 😬 

I'll take a look tonight, but yeah, I imagine that'll fix it.

It might be an idea to pop a warning in the console for such a scenario, you know, to make it idiot-proof for fools like me!

**Comment by verlok** [comment]
That’s good to hear. 

> It might be an idea to pop a warning in the console for such a scenario, you know, to make it idiot-proof for fools like me!

You’re right, a warning would be useful, and there are many scenarios where it would, but my question is: it is worth it? Is it worth adding control statements and error strings to this script’s code, making it heavier to download and slower to execute, just to make mistakes more evident? And would the script utilisers notice them? Because believe me, from my past experience as this script maintainer, I noticed that only a percentage of LazyLoad utilisers know about the existence of the browser’s developer tools or know what the console is. 

I try and keep this script light and fast, so I believe that, for now, a thorough documentation and GitHub issues are enough. 

What do you think?

**Comment by jasewarner** [comment]
Totally up to you, of course – I'm not privy to the number of scenarios that you would need to cater to in the form of warnings.

I just feel bad for you when you have to provide support for simple mistakes like the one in this thread! ✌🏻

**Comment by verlok** [comment]
Hey @jasewarner , 
I’m glad we solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time to grow and evolve.

Thank you for thinking about it. 

Have a nice day!
