### ISSUE TITLE
Display the default pictures in RSS client.

### ISSUE THREAD

**Issue by tsq456** [verlok/vanilla-lazyload#525]
**Is your support request related to a problem? Please describe.**
I use Lazyload on my personal blog. Below is my Lazyload HTML code and JS configuration code:

```html
<img
  src="/images/lazyload.gif#center" 
  data-src="{{ $thumb }}" 
  class="zoom lazy" 
  alt="{{ $title }}"
/>
```

```javascript
var myLazyLoad = new LazyLoad();
myLazyLoad.update();
```

My blog has RSS enabled, but when I browse the articles in the RSS client, I find that all pictures show the default pictures(`src="/images/lazyload.gif#center"`) instead of the loaded pictures(`data-src="{{ $thumb }}"`).
Is there a way to display the loaded picture in the RSS client?

**LazyLoad version**
- Version 17.3.1

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: Chrome
 - Version 90.0.4430.212

**Screenshots**
![image](https://user-images.githubusercontent.com/18387796/118426161-49702700-b6fd-11eb-944e-5d0f1b64903a.png)

**Comment by verlok** [comment]
Hey @tsq456,
that's why the `img` tag you are using in the RSS feed is the same you use in your HTML.
My suggestion would be to use the real image tag in the RSS feed you're generating, that should be different from the image you're using in your HTML.
Let me know what you think!

**Comment by tsq456** [comment]
Thanks for your advising!

Because I'm using HUGO to generate my blog and the RSS feed, so I have to figure out if HUGO support such feature.

**Comment by verlok** [comment]
I’m closing this for now since this is not strictly related to this JS library. 
I guess if you don’t find a way you can open an issue under the HUGO repository.
