### ISSUE TITLE
Lazyloading mask images?

### ISSUE THREAD

**Issue by Jetroid** [verlok/vanilla-lazyload#528]
Is there a way to use this library to lazyload [mask-image](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image)s in the same way that we can lazyload background-images?

P.S. Props, this is a great library and I love using it.

**Comment by verlok** [comment]
Hey @Jetroid,
thank you for asking and sorry for the delay in the reply.

What you're asking is not currently supported, but it could be easy to implement.

But before I do it, can I ask you why you would need this feature? 
Do you really have a website with many mask images, those images being heavy enough to be lazy loaded?

Thanks

**Comment by verlok** [comment]
Hey @Jetroid, 
I'm still waiting for your reply, should I assume you solved otherwise?

**Comment by verlok** [comment]
Hey @Jetroid, 
I assume you solved!

If you’re happy with the documentation you found and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
