### ISSUE TITLE
Library does not initialise correctly for images outside viewport

### ISSUE THREAD

**Issue by anders-photowall** [verlok/vanilla-lazyload#530]
**Is your support request related to a problem? Please describe.**
After upgrade from v12 to v17 only images within viewport on page load are loaded. I've narrowed it down to the upgrade from v13 to v14 (the major rewrite). We currently run vanilla-lazyload by async loading from cdn at the bottom of body. But I've also tried local install via npm (which we want to move to) and it has the same issue. In that case the "new LazyLoad" statement was put into an event-listener for DOMContentLoaded and also run last of the deferred scripts. I point that out specifically because it seems to be some kind of race-condition/timing issue. I can make it work by adding a lazyLoadInstance.update() in a setTimeout but the timeout must be approx 1.5s for the library to correctly initialise for the offscreen images. So it seems to be some kind of DOM not being ready issue. Doing a document.querySelectorAll() on the "elements_selector" right before initialising the library do return all images correctly however. 

Note that this is not consistent for all our pages, and even on the pages were the issue shows it sometimes work (but very seldom) so I'm pretty sure it's a race condition where our code somehow interfers with the library and/or the IntersectionObserver API. Any suggestions on what to look at? 

**To Reproduce**
If needed I can setup an accessible test server for you, but first would like some feedback if you just could point me in the right direction of what the issue could be (with our code). 

**Expected behavior**
Images targeted with elements_selector that are outside viewport should load when they appear in viewport.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Issue shows on v14 and up

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Edge, Chrome
 - Version 92

**Comment by anders-photowall** [comment]
Oh wow I think I just figured out what was wrong.

I finally realised the problematic pages all shared one common react component which added an image with data-src to be handled by lazyload. This component ran lazyloadInstance.update(document.querySelectorAll({componentImageClass})) which I thought would add the image to be handled by lazyload. Which it did - but since v14 also threw away all observation of images that did not have "componentImageClass". 

So either lazyLoadInstance.update() before v14 just ignored any argument passed to it and I just thought it had an effect or it was an undocumented breaking change in v14, but I suspect the former :). I'm closing this issue.

**Comment by verlok** [comment]
Hey @anders-photowall,
thank you for reporting the issue and the feedback. 
What was the resolution you applied, in the end?

**Comment by anders-photowall** [comment]
Hi @verlok, thanks for a great library :). 

The resolution was to let the problematic react component run lazyLoadInstance.update() without any arguments. 

For this use case, i.e. having asynchronously added DOM elements that should be handled by the library it would be great with a method to add images to the current lazyLoadInstance without having to do a complete update(). Knowing how the internals work, would you say it's a big performance issue to run update() several times? We have created a "LazyImage" component which uses your library under the hood, but if we start using it extensively we would call update() a lot. Once for each image using that component which also has some kind of async fetch of data before image is rendered so that the initialisation of the lazyLoadInstance is already complete.

Building the LazyImage component this way was sort of a shortcut as our page is a hybrid of newer react components and legacy templated html, which has used your library for a long time. Perhaps it might be worthwhile to not actually use your library for such a react component and instead directly interface with the IntersectionObserver API? It's fairly easy to find example code for a "useIntersectionObserver" hook for example.

**Comment by verlok** [comment]
Hey @anders-photowall,

sorry about the very late reply, it was an intense summer here 😅

Given the rest of your page already uses LazyLoad, I’d recommend to use the same library instead of a useIntersectionObserver hook. 

Calling the `update` method several times shouldn’t be a big problem, because it’s internally optimized, but it’s always better to call it less and better. 

If you think you found a bug in this library, please reopen the issue and help me reproducing the issue step by step, even better if you are able to reproduce the issue on a [codesandbox](https://codesandbox.io/).
