### ISSUE TITLE
Way to make images disappear or unload when page is scrolled?

### ISSUE THREAD

**Issue by MrMerkin** [verlok/vanilla-lazyload#535]
Hi

Just started using this script. Works great, is tiny, and was easy to setup. Love that it works on background images.

I'm curious if there's an easy way to make images go to `opacity: 0` if the page is scrolled to where the images go out of view? This could be useful for long, image-heavy pages (something I'm working with right now), especially using large images with large high DPI screen. Some lag shows up in some browsers after everything has loaded.

I assume this can be done with an `eventListener` to detect when the image or element is completely off-screen, and maybe swapping classes or something, so instead of a fade that would eat up CPU, it would just set `opacity` to `0`. If the image or element enters view again, classes would swap back (or a new class swapped) and the `opacity` would be at `1` (hopefully without being noticed).

### To clarify
1. page load
2. scroll down
3. lazyload/fade in
4. scroll down again
5. image out of view, opacity to 0
6. scroll up
7. image back in view, opacity to 1

I don't have much experience with Javascript and the DOM, and would appreciate a point in the right direction on how to integrate this with lazyload, or something similar to deal with many images. Maybe this approach wouldn't help. I don't know if unloading is preferred (maybe it will still be cached in the browser?)  and then lazyload/fade in again, or doing this `opacity` change. Main thing is for performance so mobile devices and large monitors with high dpi screens don't lag out.

Thanks

**Comment by verlok** [comment]
Hey @MrMerkin ,
thank you for opening this.

If you [check the options](https://github.com/verlok/vanilla-lazyload#options) you'll see you have both the class `class_exited` and the callback `callback_exit`.

The default value of `class_exited` is `lazy-exited` so you'd probably just need to set the opacity in your CSS, like this:

```css
.lazy-exited {
  opacity: 0
}
```

Easy peasy?

Let me know if that worked for you.

**Comment by MrMerkin** [comment]
Man, you thought of everything. 

Seems easy enough, but I think I'm just an idiot :P

I modified your example code and added threshold to suit the page. I don't see the `lz-exited` class being added to anything when I scroll (using Firefox Dev Tools) and I don't see any exited messages in the Console.

Is there some other setting I'm missing?

```javascript
(function() {
	function logElementEvent(eventName, element) {
		console.log(Date.now(), eventName, element.getAttribute("data-src"));
	}

	var callback_enter = function(element) {
		logElementEvent("🔑 ENTERED", element);
	};
	var callback_exit = function(element) {
		logElementEvent("🚪 EXITED", element);
	};
	var callback_loading = function(element) {
		logElementEvent("⌚ LOADING", element);
	};
	var callback_loaded = function(element) {
		logElementEvent("👍 LOADED", element);
	};
	var callback_error = function(element) {
		logElementEvent("💀 ERROR", element);
		element.src = "https://via.placeholder.com/440x560/?text=Error+Placeholder";
	};
	var callback_finish = function() {
		logElementEvent("✔️ FINISHED", document.documentElement);
	};
	var callback_cancel = function(element) {
		logElementEvent("🔥 CANCEL", element);
	};

	var ll = new LazyLoad({
	    elements_selector: ".lazy",
		threshold: 100,
		class_applied: "lz-applied",
		class_loading: "lz-loading",
		class_loaded: "lz-loaded",
		class_error: "lz-error",
		class_entered: "lz-entered",
		class_exited: "lz-exited",
		// Assign the callbacks defined above
		callback_enter: callback_enter,
		callback_exit: callback_exit,
		callback_cancel: callback_cancel,
		callback_loading: callback_loading,
		callback_loaded: callback_loaded,
		callback_error: callback_error,
		callback_finish: callback_finish
	});
})();
```

**Comment by verlok** [comment]
Hi again,
no @MrMerkin you're not an idiot :)

You're missing the `unobserve_entered` option, which defaults to `true` and it means "when the images have entered the viewport and they are loaded, stop watching them".

So you need to add `unobserve_entered: false` to the options object if you want LazyLoad to keep watching the images and that class to be added on exit.

Sorry for not mentioning it before!

**Comment by MrMerkin** [comment]
Ah! Thanks man. I'll give it a whirl.

**Comment by verlok** [comment]
Let me know how it goes!

**Comment by verlok** [comment]
By the way, let me just add something here:

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day (or night)!

**Comment by MrMerkin** [comment]
It worked!... but not how you said. I had to add `unobserve_completed: false`. I guess that keeps the listener alive.

`unobserve_entered: false` was already set in the defaults. 

The `lz-exited` class is now being added. CSS was easy to work out with a short transition, and everything is working as I'd hoped. If you scroll up and down like a madman, there can be a little fps spike, but that's expected. Normal scrolling works way better now. Before this sometimes it would jump a few hundred pixels.

Thanks for the help and the great script. I thought it was going to be nightmare to get lazy loading to work in my project. If I'm not broke in the near future I'll try to send you a few bucks. 👍🏻

**Comment by verlok** [comment]
Cool! 

If you need more advice on how to optimize performance, just pop by opening another issue.
Closing this now.

> If I'm not broke in the near future I'll try to send you a few bucks.

I hope you're not broke! And [a coffee](https://ko-fi.com/verlok) is still quite cheap, these days ;)

**Comment by MrMerkin** [comment]
One note to add, but you can keep this closed.

There are some images that aren't obeying the CSS for exiting, so they don't fade out and in again. They are images inside nested `<div>`s and some of those `<div>` are `display:flex`.  Not sure if that's causing the problem or if it's the order of my CSS classes. If I can't figure out I'll pop back in, but I'm guessing it's just a CSS thing.

**Comment by verlok** [comment]
Yeh, check out that CSS specificity :)
To see if the script is working you just need to watch the DOM for the CSS classes added and removed by lazyload.
