### ISSUE TITLE
Quick question about multiple srcset

### ISSUE THREAD

**Issue by MrMerkin** [verlok/vanilla-lazyload#540]
Sorry to bother you again but I was just curious if lazyload works ok if you have a `<picture>` with numerous `<source>` elements with multiple `data-srcset` and `sizes` for fine-tuning size breakpoints for art direction, and using webp with jpg/png fallbacks. Like if you have 10-15 `data-srcset` and `sizes` for both webp and jpg in 1 `<picture>` element, will this work?

I have to rewrite a large php function in order to test this and just want to make sure it will work okay with lazyload before I spend the hours coding it. So far it is working great with a normal simple setup and browsers that support webp are using them and lazyloading them.

Thanks

**Comment by verlok** [comment]
Yes, it would work. 😅

**Comment by MrMerkin** [comment]
Awesome 👍🏻
