### ISSUE TITLE
Lazyload on iframes causing extra history states (info)

### ISSUE THREAD

**Issue by MrMerkin** [verlok/vanilla-lazyload#542]
I know you're probably sick of seeing my avatar, but I tracked down this bug today. I think it's related to the ads being served in iframes using lazyload, but it only happens with iframes that have lazyload applied. If I delete the lazyload class the behavior stops. I contacted the ad company and they said they setup a filtering of ads that may be causing this, but they didn't say what the problem was, but I felt it would be good to bring to your attention.

Visiting any page that has them creates 3-5 additional history states for that page. In Firefox and Brave, I'm not seeing the additional history states in the history window, but click-hold the back button to show the recent history menu and the extra states are there. Hitting the back button causes a quasi infinite loop where you can't get back the previous page because new history states are being created every time the page loads.

Not sure if you've ever run into this, but thought it wise to share in case you run into it or another user does. I'll try to get more info out of the ad provider to find out why this is happening.

Feel free to close this after reading.

**Comment by verlok** [comment]
Thank you for reporting. 
Not sure the bug has something to do with this script. There is a collision between the two, but this script doesn’t do anything with page or history states. 
What is the ads provider?

**Comment by MrMerkin** [comment]
Adsterra is the provider.

One thing I noticed is that they are serving cookies with `Samesite:none`, but they are leaving off the `Secure` attribute. Generates warnings in Firefox that the cookie has or will be rejected. Maybe their script it's trying to reload the iframe content to serve a new cookie or something and then lazyload is helping it do that. idk

Their filtering failed, so I sent them a bunch of screenshots and info and a link to the repository to see if they can find the conflict, and they passed it along to the higher-ups. I'll keep you posted.

**Comment by verlok** [comment]
Thanks. 
since it’s not an issue of this script, I’ll close the issue.

**Comment by MrMerkin** [comment]
Just wanted to add a note here that I finally verified this bug had nothing to do with lazyload after exhausting all options. After creating static HTML pages with the ads locally and server-side, bug persists, so it's a bug in the ads themselves and nothing to do with the script or how I use it in WordPress.

**Comment by verlok** [comment]
Hey @MrMerkin 
thank you very much for the update! I’m glad this library has nothing to do with your issue!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
