### ISSUE TITLE
How to lazy load images in swiper that are not yet in viewport?

### ISSUE THREAD

**Issue by gitbrutus** [verlok/vanilla-lazyload#544]
**Is your support request related to a problem? Please describe.**
I am using swiper and only the image that's currently the viewport lazy loads, the other ones only load after swiping. I'm suspecting that this is intentional, but it creates a bad UX if each image only loads when it is swiped into the viewport (= delay). I also tried to use scrollingPanel solution (by adding a div around swiper and/or within swiper). Doesn't work either.

**To Reproduce**

```html
<!-- Swiper -->
<div class="row text-center swiper" style="max-height: 100%;">
   <div class="swiper-container">
      <div class="swiper-wrapper d-flex my-auto">
         <div class="swiper-slide">
            <img class="lazy image_1 img-fluid swiper-900px"
            src="https://via.placeholder.com/1000x560?text=persona1_backup"
            data-srcset="https://via.placeholder.com/1000x560?text=persona1 600w,
                         https://via.placeholder.com/1000x560?text=persona1_large 1000w"
            >
         </div>
         <div class="swiper-slide">
            <img class="lazy image_1 img-fluid swiper-900px"
            src="https://via.placeholder.com/1000x560?text=persona2_backup"
            data-srcset="https://via.placeholder.com/1000x560?text=persona2 600w,
                         https://via.placeholder.com/1000x560?text=persona2_large 1000w"
            >
         </div>
      </div>
      <div class="swiper-pagination"></div> <!-- Add Pagination -->
      <div class="swiper-button-prev"></div> <!-- Add Arrows -->
      <div class="swiper-button-next"></div> <!-- Add Arrows -->
   </div>
</div>
<!-- Swiper end -->
```

**Expected behavior**
Once the first image in swiper is in viewport, all images in that swiper should load instantly (that the user can swipe without loading delay for each image)

**LazyLoad version**
Please report which version of LazyLoad you're using.
17.5.0

**Desktop (please complete the following information):**
Chrome, Firefox

**Screenshots**
![image](https://user-images.githubusercontent.com/30526328/138526382-f4b192e2-ca3d-48e7-a142-72e04c2ebe13.png)
![image](https://user-images.githubusercontent.com/30526328/138526438-3765c7fd-8969-4038-bce7-11c666d30369.png)

**Additional context**

**Comment by verlok** [comment]
@gitbrutus, did you have the chance to test it?

**Comment by verlok** [comment]
Hey @gitbrutus, 
I’m going to assume you silver and I’m closing this. Feel free to reopen otherwise. 

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!

**Comment by verlok** [comment]
Just another post on this issue to send the correct url for the a I've demo, as it has recently changed:
https://verlok.github.io/vanilla-lazyload/demos/swiper.html

**Comment by verlok** [comment]
Audi check out the blog post on by blog where I put this all together
https://www.andreaverlicchi.eu/blog/lazyload-swiper-images-instances/

**Comment by janaipakos** [comment]
Something that I find confusing about the lazyload-swiper-images-instance above is that there are already elements that are downloaded that match the lazyloaded element. An example is `S02e05`. Its been downloaded four times already despite only one being visible? And scrolling to `S02e05` will show its being downloaded/lazy-loaded correctly. Am I reading the network bar wrong, or is the lazy-loading not working if everything is downloaded on page load?

**Comment by verlok** [comment]
Hello @janaipakos
I read your message 4 times and opened the live demo, but I'm not sure I understand what you mean. 
Could you be more specific, maybe providing screenshots?

**Comment by stanleyxu2005** [comment]
I have a similar usage with `swiper` (v11) but I dont have any problem with `vanilla-lazyload`. 

Here are the related code in my approach.
1. Add `loading="lazy"` (or `class=lazy`) in every image inside swiper slide. 
2. Rename `src` to `data-src`; `srcset` to `data-srcset`
3. By initialiating `LazyLoad`, make sure the `elements_selector` is set to the correct image selector
4. Make sure `lazyload.update()` is called when the swiper slide is mounted

Hope this works.
