### ISSUE TITLE
Hi, I need eliminate lazy load into www.revistaseguridad360.com but i dont know how can do it

### ISSUE THREAD

**Issue by revistaseguridad360** [verlok/vanilla-lazyload#545]
I need eliminate lazy load into [www.revistaseguridad360.com](www,revistaseguridad360.com) but i dont know how can do it. I have a plugin to accelerate web, but the original (core= lazy load functions in wordpress I dont know how can eliminate it.

Thanks in advance for you help.

**Comment by verlok** [comment]
Hey @revistaseguridad360, 
I’m going to assume you solved and close this, but feel free to reopen if you still need help.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
