### ISSUE TITLE
Threshold not working with callbacks

### ISSUE THREAD

**Issue by andre-brdoch** [verlok/vanilla-lazyload#549]
**Describe the bug**
`threshold` doesn't seem to affect callback functions (`callback_enter`, `callback_exit` etc). I am not sure weather this is a bug!

If this is intended, it would be awesome if there were separate callbacks that explicitely consider threshold, eg `callback_threshold_enter` and  `callback_threshold_exit`!

**To Reproduce**
```js
const LazyLoad = require('vanilla-lazyload');

  new LazyLoad(
    {
      threshold: 1000, // <-- put some large threshold value
      callback_enter: () => {
        console.log('i should trigger 1000px early!!');
      },
      callback_exit: () => {
        console.log('i should trigger 1000px late!');
      },
    },
    [ el ],
  );
// will execute exactly when element is entering/leaving the viewport, ignoring the threshold
```

**Expected behavior**
Threshold should affect callbacks like it does affect image elements.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.1.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 95

**Additional context**
We are considering using this library not only for loading images, but also as a replacement for [in-view](https://github.com/camwiegert/in-view) and [AOS (animate on scroll)](https://michalsnik.github.io/aos/). We want to be able to hook in when elements (not only images) are entering/leaving the viewport (or are about to). This library does an excellent job, and we dont see why we need 3 different libraries that are all centered around doing the same thing - detecting when something is in view or not 😄

**Comment by verlok** [comment]
Thank you @andre-brdoch,

I guess this is a pretty big one. Let me verify this and I’ll get back to you.

**Comment by verlok** [comment]
@andre-brdoch , I've tried this demo here
https://www.andreaverlicchi.eu/vanilla-lazyload/demos/thresholds.html
where 3 instance of LazyLoad are instantiated (as you click the buttons) 
but I wasn't able to reproduce the issue you've opened.

Are you able to isolate the problem in a new demo, like on Codepen or Codesandbox?

**Comment by verlok** [comment]
I did it :)

I've used your code and created the following codepen.
https://codepen.io/verlok/pen/dyzLvWv?editors=1010

The callbacks are fired when expected.

**Comment by verlok** [comment]
Same when passing a second argument with a Nodeset value as a second parameter to the `new LazyLoad` constructor.
https://codepen.io/verlok/pen/MWvRpEN?editors=1010

**Comment by verlok** [comment]
@andre-brdoch, would you able to isolate the problem in a Codepen or Codesandbox, so I can check?

**Comment by verlok** [comment]
Hey @andre-brdoch,
I didn’t hear back from you so I’m going to assume you solved your issue.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
