### ISSUE TITLE
[Error] Failed to load resource: Response served by service worker is opaque

### ISSUE THREAD

**Issue by datapolitical** [verlok/vanilla-lazyload#551]
I've added vanilla-lazyload to my website but when I try to preconnect to speed up loading I get 
```"[Error] Failed to load resource: Response served by service worker is opaque (lazyload.min.js, line 0)"```

This is the code I'm using to pre-load: 
```
<link rel="preload" crossorigin="anonymous" as="script" href="https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.5.0/dist/lazyload.min.js" integrity="sha256-chZm2VfM5r7hxFu6TGArcJmYU+Y19fT+mg58IBVCtdU=">
```

And this is the code I'm using to actually load the script:
```
<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.5.0/dist/lazyload.min.js" integrity="sha256-chZm2VfM5r7hxFu6TGArcJmYU+Y19fT+mg58IBVCtdU=" type="text/javascript" crossorigin="anonymous"></script>
```

I've tried following the instructions I've found online but even while doing so I still get the opaque message and this
```
[Warning] The resource https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.5.0/dist/lazyload.min.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing. (x2)
```

Any help is greatly appreciated.

**Comment by verlok** [comment]
Hey @datapolitical 
sorry I missed this message. 

Do you still need help on this issue?

**Comment by datapolitical** [comment]
> Hey @datapolitical 
> 
> sorry I missed this message. 
> 
> 
> 
> Do you still need help on this issue?

Yes I'm still having trouble figuring out what the right approach is. I'm currently using this: <link rel="preload" as="script" href="/assets/js/lazyload.min.js" />

**Comment by verlok** [comment]
I ran into the same issue with service workers some time ago. 

I might be wrong, but I remember correctly, it has something to do with the response coming from a different domain. 

Have you tried self-hosting my script in your same domain?

**Comment by verlok** [comment]
(the solution you seem to have posted above is hidden; make sure you escape your html with a triple backtick (`) in a separate line)

**Comment by verlok** [comment]
Have you looked at this?
https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests

**Comment by datapolitical** [comment]
> Have you looked at this?
> 
> https://developers.google.com/web/tools/workbox/guides/handle-third-party-requests

Yeah I worked off of this, it looks like I did end up doing is hosting it on my own domain. My problem with this is worrying about if I ever get updates.

**Comment by verlok** [comment]
Hey @datapolitical 

Do you still need help with this issue?
 If not, how did you solve?

**Comment by datapolitical** [comment]
I copied the script to my own server. Loading it from the same origin solves the problem.

**Comment by verlok** [comment]
Hey @datapolitical 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
