### ISSUE TITLE
add an example of working with if all instances Swipers with different settings

### ISSUE THREAD

**Issue by Summersby89** [verlok/vanilla-lazyload#552]
The documentation contains an example of lazy loading of several Swipers with the same settings. What should I do if all instances of Swiper settings are different?

**Comment by verlok** [comment]
First idea: create a mapping object, ID to settings, then use the settings you get from the map by the id of the lazy swiper . 

Second idea: store the settings in the data attribute of the lazy swiper and read settings from there when the lazy element need to load

what do you think?

**Comment by Summersby89** [comment]
Thanks for the ideas! I tried to do it this way, but it doesn't work correctly:

`<div class="swiper gallery__slider swiper-lazy" id="swiperLazy1">
<div class="swiper events__slider swiper-lazy2" id="swiperLazy2"
const lazyLoadInstances = [];

const myLazyOne = new LazyLoad({
  elements_selector: ".swiper-lazy",
  unobserve_entered: true,
  callback_enter: function (swiperElement) {
    new Swiper("#" + swiperElement.id, gallerySlider);
  }
});

const myLazyFree = new LazyLoad({
  elements_selector: ".swiper-lazy2",
  unobserve_entered: true,
  callback_enter: function (swiperElement) {
    new Swiper("#" + swiperElement.id, eventsSlider);
  }
});

const gallerySlider = {
  slidesPerView: 1,
  slidesPerColumnFill: 'row',
  spaceBetween: 50,
  observer: true,
  observeParents: true,
  observeSlideChildren: true,
  grid: {
    fill: 'row',
  },

  pagination: {
    el: '.swiper-pagination',
    type: 'fraction',
    clickable: 'true',
  },
  navigation: {
    nextEl: '.swiper-button-next',
    prevEl: '.swiper-button-prev',
  },
  on: {
    // LazyLoad swiper images after swiper initialization
    afterInit: (swiper) => {
      new LazyLoad({
        container: swiper.el,
        cancel_on_exit: false
      });
    }
  }
};

const eventsSlider = {
  slidesPerView: 1,
  spaceBetween: 30,
 const projectsSlider = {
  slidesPerView: 1,
  spaceBetween: 30,
  navigation: {
    nextEl: '.projects__slider-button-next',
    prevEl: '.projects__slider-button-prev',
  },
  breakpoints: {
    668: {
      slidesPerView: 2,
      spaceBetween: 30,
    },
    1024: {
      slidesPerView: 2,
      spaceBetween: 50,
    },
  on: {
    // LazyLoad swiper images after swiper initialization
    afterInit: (swiper) => {
      new LazyLoad({
        container: swiper.el,
        cancel_on_exit: false
      });
    }
  }
};
  on: {
    // LazyLoad swiper images after swiper initialization
    afterInit: (swiper) => {
      new LazyLoad({
        container: swiper.el,
        cancel_on_exit: false
      });
    }
  }
};

**Comment by verlok** [comment]
Hey @Summersby89 
sorry I forgot to reply to you. 

Do you still need help with this issue?
If not, how did you solve?

**Comment by Summersby89** [comment]
Good afternoon, yes, help is still needed, my idea could not be implemented, my example solution does not work.

**Comment by verlok** [comment]
Hey @Summersby89,
I didn't try your code, but it seems broken to me, are you sure you copy-pasted it correctly?
Anyway the idea behind it seems to be correct, you probably need to adjust it a little bit.
Do you still need help with this?

**Comment by Summersby89** [comment]
Спасибо за обратную связь, @verlok! Thanks for the feedback! Yes, there may be a typo in this code. More help with this is not required, since Swiper also offers lazy loading. Help with is no longer needed, I did a lazy loading only for the heaviest slider. Please, in future versions, still make an example for sliders with different settings.

**Comment by verlok** [comment]
Super, @Summersby89 
I’m going to close this issue because you don't need assistance anymore.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it.
Have a wonderful day!
