### ISSUE TITLE
can we have attribute for thresholds   ie. data-threshold

### ISSUE THREAD

**Issue by Dushyant1295** [verlok/vanilla-lazyload#553]
Hi 👋  I need to call function on scroll when particular  element come into view port,   but the threshold is fixed in lazyload initialization I want different threshold   to trigger the callback function for any  specific element how can we do that  can we  have  attribute   ie.      data-threshold="200"  

    <div class="border lazy" data-lazy-function="foo"> Lazy triggered</div>

```
var lazyLoadInstance;

function createLazyLoad() {
  lazyLoadInstance = new LazyLoad({
    elements_selector: ".lazy",
    threshold: "-200",
    unobserve_entered: true, // <- Avoid executing the function multiple times
    callback_enter: executeLazyFunction // Assigning the function defined above
  });
}

function destroyLazyLoad() {
  lazyLoadInstance.destroy();
  console.log("lazy load instance destroyed");
}


window.lazyFunctions = {
  foo: function (element) {
    element.style.color = "red"
  }
};

function executeLazyFunction(element) {
  var lazyFunctionName = element.getAttribute("data-lazy-function");
  var lazyFunction = window.lazyFunctions[lazyFunctionName];
  if (!lazyFunction) return;
  lazyFunction(element);
}
```

**Comment by verlok** [comment]
You can already have negative threshold using the `thresholds` option.

**Comment by verlok** [comment]
Or maybe you can simply use the `threshold` option, passing a negative integer. (you’re passing a string in the example you posted above)

**Comment by Dushyant1295** [comment]
Can we provide threshold in html element as attribute so it can be more specific to element

**Comment by verlok** [comment]
I’m afraid that would be impossible since the threshold is an option of the observer. 

But if you could create N instances of LazyLoad, each one to observe a different set of elements, each one with a different value for the `threshold` option.

**Comment by Dushyant1295** [comment]
I think of that but is that good approach in the performance point of view 

If I've to create 10 lazyload instance  for dif thressholds   ?

**Comment by verlok** [comment]
I can’t see why it would be a bad choice in terms of performance :)

**Comment by Dushyant1295** [comment]
Yes it's not  but  it would be great if we have an option for that too

**Comment by verlok** [comment]
It’s just that it’s not something that this script controls. It just passes the threshold option to the browser’s IntersectionObserver API.

**Comment by Dushyant1295** [comment]
Yes I understand thanks for this great library

**Comment by verlok** [comment]
Hey @Dushyant1295  
I’m glad you understand and you like my library!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
