### ISSUE TITLE
How best to support netflix style layout

### ISSUE THREAD

**Issue by Matt-Pilott** [verlok/vanilla-lazyload#554]
Is there a recommended approach for a page that has multiple horizontal scrolling rows of cards like netflix?

Do i simply register lazyload on the page as a whole, or should it be an instance per row?

**Comment by verlok** [comment]
Hey @Matt-Pilott 
thank you for opening this. 

Good question!

If your horizontal scroll uses JS controls e.g. an instance of Swiper JS or other swipy library, I’d go for multiple instances LazyLoad, to be instantiated as they are about to enter the viewport. 

If the horizontal scrolling is made using pure CSS, snap scrolling etc, it’s probably a good idea to use a single LazyLoad instance for the whole page.  

Go to the readme file and search for this demos in the demos section:

- Lazily create lazyload instances 
- Lazily create Swiper instances and lazily load Swiper images

These tho are very specific about your use case, and you can see their code or try them live. 

Let me know what you think!

**Comment by Matt-Pilott** [comment]
Thanks for getting back to me, im using all css scroll snap. How does threshold work with this type of setup where i have 10 rows of scrollable cards and im generally showing 2 or 3 cards in the viewport (made for mobile only). Does threshold extend into each overflow auto row or is it just for the page scroll?

**Comment by verlok** [comment]
Hey @Matt-Pilott,

I confirm you can use a single instance of lazyload, and I've added a new demo named **Lazy load images in CSS-only horizontal sliders (Netflix style)** to prove that. Here are [the code](https://github.com/verlok/vanilla-lazyload/blob/master/demos/sliders_css_only.html) and [the live demo](https://www.andreaverlicchi.eu/vanilla-lazyload/demos/sliders_css_only.html) (also linked in the README file).

> How does threshold work with this type of setup where i have 10 rows of scrollable cards and im generally showing 2 or 3 cards in the viewport (made for mobile only). Does threshold extend into each overflow auto row or is it just for the page scroll?

The first one. Threshold extends into each overflow auto row. You can also specify two different values for threshold, horizontal and vertical, using the `thresholds` (plural) setting. Beware that you need to pass a string with the CSS unit in that case, like this: `thresholds: "300px 500px"`, whereas the `threshold` option only accepts an integer, like this: `threshold: 300`.

Let me know what you think, and if you have any more questions, here I am.

**Comment by Matt-Pilott** [comment]
Oh thank you so much! Is `threshold: 300` the same as `thresholds: "300px 300px"` ?

**Comment by verlok** [comment]
> Is `threshold: 300` the same as `thresholds: "300px 300px"`?

Yes, it is.
 So will you use a single instance of LazyLoad?

**Comment by Matt-Pilott** [comment]
Yes i will use a single instance, thanks!

**Comment by verlok** [comment]
Hey @Matt-Pilott  
I’m glad you found the best solution for your request!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!

**Comment by Matt-Pilott** [comment]
You got it!

**Comment by verlok** [comment]
Thanks Matt! You rock 🤟🏼
