### ISSUE TITLE
support Tailwindcss background classes

### ISSUE THREAD

**Issue by weilinzung** [verlok/vanilla-lazyload#556]
When using utility-first class framework, it is not possible to do lazy load as well.
https://tailwindcss.com/docs/background-image

May it be possible to add a new option like ‘data-bg-class=“custom-bg-class”’?

This new option would basically convert the Tailwindcss background image class(url with image) into something similar to the current background lazyload.

And this way would useful not only for Tailwindcss, we can do that directly from css to create a custom class for shareable, then we can repeatable use it for many places we want.

Thanks!

**Comment by verlok** [comment]
Hey @weilinzung 
thank you for opening this. 

I took a look at the tailwind documentation, but I didn’t find anything related to images too LazyLoad, except SVG patterns. 

Could you be more specific, maybe adding a more detailed example?

Thanks

**Comment by weilinzung** [comment]
Hi @verlok.

I meant when using classes with background image, then has no way to use with vanilla-lazyload.

Here is the simple usage of how background class with Tailwindcss.

https://tailwindcss.com/docs/background-image#customizing-your-theme

```
module.exports = {
  theme: {
    extend: {
      backgroundImage: {
        'hero-pattern': "url('/img/hero-pattern.svg')",
        'footer-texture': "url('/img/footer-texture.png')",
      }
    }
  }
}


<div class="shadow-lg hero-pattern"></div>
```

or 

```
<div class="bg-[url('/img/hero-pattern.svg')]">
  <!-- ... -->
</div>
```

**Comment by verlok** [comment]
Sorry @weilinzung but I still fail to understand how the element should change when entering the viewport. 

You would like the div:

```html
<div class="shadow-lg"></div>
```

to gain the `hero-pattern` class, like that

```html
<div class="shadow-lg hero-pattern"></div>
```

after it entered the viewport?

**Comment by weilinzung** [comment]
hi @verlok,

Basically there is no way I can lazy load image backgrounds if they are defined in the classes. The simple workaround I am doing is move the background out of the classes, and used as the normal way.

thanks.

**Comment by verlok** [comment]
Yes, it’s like you said. 
So I will close this issue for now, as you can already do that with LazyLoad.
