### ISSUE TITLE
README claims 2.4kB; JSDelivr serves 13.7kB

### ISSUE THREAD

**Issue by Leland** [verlok/vanilla-lazyload#557]
The README had a notice added two years ago in 68fc262 stating that Lazyload clocks in at 2.4kB. 

But when you follow the "easiest way to use LazyLoad", the JSDelivr CDN, the file you load is one that's 13.7kB. gzipped it gets down to 5.5kB: https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.5.0/dist/lazyload.min.js

Did the built library grow in size in the last couple years? Is the JSDelivr version erroneously large?

Backup of the JSDelivr file: [vanilla-lazyload@17.5.0.js.zip](https://github.com/verlok/vanilla-lazyload/files/7916343/vanilla-lazyload%4017.5.0.js.zip)

**Comment by verlok** [comment]
Hey @Leland ,
thank you for asking.

The library is now weighting 3.3 kB for the IIFE version, and 3.4 kB for the UMD version.

<img width="570" alt="Screenshot 2022-01-23 at 18 18 47" src="https://user-images.githubusercontent.com/1127721/150690143-f352178d-44c4-4202-952a-ae636bb7247f.png">

The reason why I removed the 2.4 kB statement is that I didn't want to update the gZipped file size in the README every time I released a new version.

But it's still very slim, isn't it?

**Comment by Leland** [comment]
Any ideas why the JSDelivr version is larger?

Also, if you plan on keeping that in the README, I'd definitely encourage clarifying that that's gizpped! I assumed it was minified but uncompressed :)

**Comment by verlok** [comment]
In the screenshots above the two files are downloaded from JSDelivr.

**Comment by Leland** [comment]
Aha, figured out the discrepancy. I was loading the file directly on JSDelivr and inspecting total bytes transferred over the network... which apparently also includes the favico! I am also seeing that it's clocking in at 3.4kB. Thanks!

**Comment by verlok** [comment]
Hey @Leland, 
I’m glad you figured out the discrepancy!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful week!
