### ISSUE TITLE
[BUG] debugger statements

### ISSUE THREAD

**Issue by Allain55** [verlok/vanilla-lazyload#559]
**Describe the bug**
Multiple `debugger` statements were pushed with the latest release

**To Reproduce**
See: https://github.com/verlok/vanilla-lazyload/commit/7c133133bedb0fdd106078aea213c19717388eea

**Expected behavior**
Debugger statements shouldn't exists in the production version of LazyLoad

**LazyLoad version**
- Version 17.6.0

**Comment by verlok** [comment]
Thanks for reporting @Allain55.
Fixed in 17.6.1.
