### ISSUE TITLE
Can I fade in videos on load as well?

### ISSUE THREAD

**Issue by m42444** [verlok/vanilla-lazyload#561]
Hi, I am using the css fade in method for images and it works fine. But I tried to also let videos fade in as they finished loading. I used the same css properties like in the example for images. 

Even when I let the videos load on pageload and then just bring them into view, they are appearing instantly.

Thank you for any help! :)

**Comment by verlok** [comment]
Hey there @m42444 
are you using poster images in your videos?
Do you have autoplay?

In other words, can you share some of your HTML code, maybe anonymising the URLs?

Can you isolate the demo on a Codepen or Codesandbox page?

**Comment by m42444** [comment]
Hey @verlok, 
thanks for getting back to me so quickly!
Before I set up a codepen: Yes, I am using autoplay and also have a poster image assigned. Is there a problem with that? 

Thank you!

**Comment by verlok** [comment]
No problems with that, I was just trying to understand. 

if you want you could try and disable the autoplay and see what happens. That’s because you could play the video using JavaScript, after the fade in has been completed.

**Comment by m42444** [comment]
Alright, I tried but nothing changed so far.. I will set up a codepen. :)

**Comment by verlok** [comment]
Another attempt could be to change the videos to be just images (using the poster images), fade them in, then replacing them with an autoplay video after the fade-in effect finished.

**Comment by m42444** [comment]
Thanks, sounds good. Here is my codepen, it's a slider where you can click on the left and right side to skip through the slides : https://codepen.io/m42444/pen/PoOXxbG 

The slides will also fade on click but it has nothing to do with the initial fade-in effect of an element. So you can see the issue with the videos on the first loop through the slides. :)

**Comment by m42444** [comment]
Hey @verlok, do you have another idea how to solve this? :)

**Comment by verlok** [comment]
Not really :-/

**Comment by verlok** [comment]
Hey @m42444 ,

Do you still need help with this issue? If not, how did you solve?

**Comment by m42444** [comment]
Hey @verlok,
thanks, I solved it by adding a callback function to every video in my code which listens for "oncanplaythrough" and then fades it in with opacity:

`window.lazyFunctions = {
    showVideo: function(element) {
        var e = element;
        e.style.opacity = 0;

        var vid = element;
        vid.oncanplaythrough = function() {
            var e = element;
            fade(e);
        };

        function fade(element) {
            var op = 0;
            var timer = setInterval(function() {
                if (op >= 1) clearInterval(timer);
                element.style.opacity = op;
                element.style.filter = 'alpha(opacity=' + op * 100 + ")";
                op += op * 0.1 || 0.1;
            }, 8);
        }

    }
}`

It works in most cases but it would definitely be cool to have this option implemented in the lazyload library. :) 
Thank you for your help anyway!

**Comment by verlok** [comment]
Hey @m42444 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
