### ISSUE TITLE
Loading prevention mechanism

### ISSUE THREAD

**Issue by nlemoine** [verlok/vanilla-lazyload#564]
**Is your feature request related to a problem? Please describe.**

I'm using `vanilla-lazyload` (coming from `lazysizes`) to lazy load things in conjuction with a custom api to handle GDPR consent.

In this context, this is quite hard to to prevent them from actually loading when user has not yet given their consent because no "loading prevention" mechanism exists, yet :)

**Describe the solution you'd like**

A loading prevention mechanism. 

`lazysizes` uses a [`lazybeforeunveil` event](https://github.com/aFarkas/lazysizes#js-api---events), which, when `defaultPrevented` (e.g. returning `e.preventDefault()`), will prevent the element from loading. 

In `vanilla-lazyload`, maybe getting the return value of the `callback_enter` function and if this value is `false` (or falsy), prevent the element to load would be a nice solution to this issue?
https://github.com/verlok/vanilla-lazyload/blob/a84fec1dcf60ab7e6be5b188782e235a4cb83bda/src/intersectionHandlers.js#L16-L17

Let me know this solution feels right to you, I can submit a PR. 

**Describe alternatives you've considered**

I managed to make this mechanism work but It brought me into dark hacky lands.  See the simplified example:
https://codepen.io/hellonico/pen/YzYNbWB

I had to add a `data-ll-status="loading"` to prevent the element from loading and remove it when user has consented. 

**Additional context**

Note that I'm using some static page caching, so checking consent et altering HTML server side accordingly isn't an option. Everything must be handled client side.

**Comment by verlok** [comment]
I’m not sure I understand.

LazyLoad doesn’t load anything automatically, it’s your code that, by using `new LazyLoad()` starts the lazy loading. 

So couldn’t you just run LazyLoad after users accepted GDPR consent?

**Comment by nlemoine** [comment]
Sorry, I shouldn't have included that consent button, It's misleading, forget about it.

Take an example of a page load that happened after user consent (which doesn't mean "load everything") with many lazy loaded items. There are images, iframes, carousels, etc. They all share a `.lazyload` selector but some of them falls under user consent and should not be loaded. And as I mentioned earlier, they have the same HTML markup whether user consented or not (static site).

I have an object which tells me what services/providers I can load/not load, something like: 
```js
const services = {
  "youtube": false,
  "vimeo": true,
  "twitter": false, 
  // etc.
}
```

How dow I prevent/filter those particular items from loading?

Sure I could do something like:
```js
const hasConsentFor = (service) => {
  // Check if we have consent for particular service
  return true/false;
}


// Remove lazyload class on unconsented items
const underConsentItems = [...document.querySelectorAll('[data-cookie-consent="youtube"]')];
underConsentItems  
  .filter((element) => {
    return element.hasAttribute('data-cookie-consent') && !hasConsentFor(element.getAttribute('data-cookie-consent'));
  })
  .forEach((element) => {
      element.classList.remove('lazyload');
  });

// Then initialize LazyLoad
const lazyInstance = new LazyLoad({
  elements_selector: '.lazyload',
});
```

But it's not the most efficient way of handling with this since this code will be executed **whether the item has been reached or not**, on each page load.

My feature request is about being able to prevent loading **when the item is intersecting**, because I can't know in advance that some item at the bottom of the page should be loaded or not. 

I hope this clarified the initial misunderstanding 😄

**Comment by verlok** [comment]
Hey @nlemoine 
sorry for the delay in this reply.

I think I have the solution for your requirement without needing to change LazyLoad.

I get you already have in your HTML markup some data attributes that specify the consent required to load that item.

So for example you have the following HTML

```html
<iframe class="lazy youtube" [data-cookie-consent="youtube"] data-src="https://youtube.com/..."></iframe>
<iframe class="lazy vimeo" [data-cookie-consent="vimeo"] data-src="https://vimeo.com/...">...</iframe> 
<iframe class="lazy twitter" [data-cookie-consent="twitter"] data-src="https://twitter.com/...">...</iframe> 
<img class="lazy image" data-src="https://your-cdn.com/..." />
```

Then in your JS code, you go:

```js
const servicesConsent = {
  "youtube": false,
  "vimeo": true,
  "twitter": false, 
  // etc.
}

Object.keys(servicesConsent).forEach(serviceKey => {
  const mustLoad = servicesConsent[serviceKey];
  if (mustLoad) (
    new LazyLoad({
      elements_selector: `lazy [data-cookie-consent="${serviceKey}"]`
    })
  )
});
```

That creates one LazyLoad instance per service the user has given consent to.

If you can, you could also use classes instead of the `data-cookie-consent` attribute, to have a shorter HTML and JS code.

What do you think?

**Comment by nlemoine** [comment]
Hello @verlok, 

Sorry for the delay, too, spring vacation kept me AFK :)

> I think I have the solution for your requirement without needing to change LazyLoad.

Thanks for the proposed solution, I really appreciate your effort for finding a solution to this. 

Also note that at anytime (after page load), a user can change his consent setting regarding a service (e.g. watch a video). While in the first workaround, I just needed to call something like: 
```js
// An input/button somewhere that allows user to agree for a service triggers this 👇
consentApi.on('allow', (service) => {
    [...document.querySelectorAll(`[data-cookie-consent="${service}"]`)];
      .filter((element) => !element.classList.contains('lazyload'))
      .forEach((element) => {
          element.classList.add('lazyload');
      });
    LazyloadInstance.update();
});
```

The new proposed workaround makes it harder / more verbose to update a service (multiple LL instances) although it could be simplified like:
```js
const servicesConsent = {
  "youtube": false,
  "vimeo": true,
  "twitter": false, 
  // etc.
}

const consentSelector = Object
  .keys(servicesConsent)
  .filter((service) => servicesConsent[service])
  .map((service) => `lazyload.[data-cookie-consent="${service}"]`)
  .join(',');

const consentLazyLoadInstance = new LazyLoad({
  elements_selector: consentSelector,
});
```
But I can't live update instance settings (to update the `elements_selector` in case consent changed for a service)? The only way is then to use `LazyLoad.load(element)`. 

All these solutions works/might work. However, they still feels like workarounds to me. 

Something like `callback_prevent` (if using a falsy returned value for `callback_enter` feels too odd) would have solved this much more nicely:
```js
dontLoad = safeCallback(settings.callback_prevent, element, entry, instance);
if (dontLoad) return;
load(element, settings, instance);
```

But I will perfectly deal with the existing options if you don't feel this way :)

**Comment by verlok** [comment]
Hey @nlemoine 
thanks for your thorough explanation.

I understand your usecase better now.

But I still think that if I implemented `callback_prevent` you be asking this script _"Hey, I want to lazyload these DOM elements"_, then when the elements effectively enter the viewport, this script ask you _"I'm about to lazyload this element, do you really want to lazy load it?"_ which really feels odd to me, because you could've said you didn't want to lazyload that DOM element from the beginning, and just update Lazy Load when you would be ready to load it. 

Does it make sense?

A couple of questions on your reply now:

> The new proposed workaround makes it harder / more verbose to update a service (multiple LL instances)

LazyLoad is multi-instance exactly for this reason, just like IntersectionObserver is. Why do you say "makes it harder / more verbose to update a service"?

> although it could be simplified like
> `[..code..]` 
> but I can't live update instance settings (to update the elements_selector in case consent changed for a service)? The only way is then to use LazyLoad.load(element).

I didn't understand the last sentence, especially the part "I can't live update instance settings", but ultimately the whole sense of the paragraph. Could you clarify?

Thanks

**Comment by nlemoine** [comment]
> Does it make sense?

Yes and no :) In a consent management context or in some specific contexts, it doesn't feel that odd to me to have a last chance, **when the element intersects**, to prevent it from loading. Consider this from an event driven point of view, it's not that weird to allow this event to be `defaultPrevented` because the "loading" part could be considered as an event. This would just provide a bit more control over the loading mechanism **after the instance** is created which is currently impossible. All workarounds we discussed works, but IMHO, I think it could be implemented so much simpler if this feature would exist natively in the library. Moreover, this feature doesn't add extra weight/performance hit to the library. 

> LazyLoad is multi-instance exactly for this reason, just like IntersectionObserver is. Why do you say "makes it harder / more verbose to update a service"?

This refers to to your following example:
```js
Object.keys(servicesConsent).forEach(serviceKey => {
  const mustLoad = servicesConsent[serviceKey];
  if (mustLoad) (
    new LazyLoad({
      elements_selector: `lazy [data-cookie-consent="${serviceKey}"]`
    })
  )
});
```

Say I'm on a long page and have a lazy element at the bottom of it. Before scrolling, I choose to deny a service. I would to register an object of all services in order to have the possibility of canceling it. 

```js
const consentInstances = {};
Object.keys(servicesConsent).forEach(serviceKey => {
  const mustLoad = servicesConsent[serviceKey];
  if (mustLoad) (
    consentInstances[serviceKey] = new LazyLoad({
      elements_selector: `lazy [data-cookie-consent="${serviceKey}"]`
    })
  )
});

consentApi.on('deny', (service) => {
    consentInstances[serviceKey].destroy();
});
```
And I would also have to create new instances and push it to the `consentInstances` for services that would be allowed. 

> I didn't understand the last sentence, especially the part "I can't live update instance settings", but ultimately the whole sense of the paragraph. Could you clarify?

Sorry, I'll try to make it more clear 😅 

Consider my one consent instance example (versus the multiple instances you proposed):
```js
const consentSelector = Object
  .keys(servicesConsent)
  .filter((service) => servicesConsent[service])
  .map((service) => `lazyload.[data-cookie-consent="${service}"]`)
  .join(',');

const consentLazyLoadInstance = new LazyLoad({
  elements_selector: consentSelector,
});
```

What if I need to add or remove a service, just like the use case mentioned above? I would need to change the `elements_selector` option which can't be done by updating the instance settings:

```js
const servicesConsent = {
  "youtube": false,
  "vimeo": true,
  "twitter": false, 
  // etc.
}

const getConsentSelector = (servicesConsent) => {
    return Object
      .keys(servicesConsent)
      .filter((service) => servicesConsent[service])
      .map((service) => `lazyload.[data-cookie-consent="${service}"]`)
      .join(',');
}

const consentLazyLoadInstance = new LazyLoad({
  elements_selector: getConsentSelector(servicesConsent),
});
consentApi.on('deny', (service) => {
    const servicesConsent = consentApi.getServices();
    consentLazyLoadInstance.updateOptions({
        elements_selector: getConsentSelector(servicesConsent),
    })
});
```

I know you will probably say I'll better destroy the instance and create a new one with updated options, which is a perfectly valid point.

**Comment by verlok** [comment]
Hey, yes, you'd better destroy the instance and create a new one with updated options :)

**Comment by verlok** [comment]
@nlemoine I'm going to close this, feel free to reopen if you feel like discussing it further.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it.
Have a wonderful day!

**Comment by nlemoine** [comment]
I'm running out of arguments, you can close this ;)

Thanks for your time. I know OSS is hard sometimes, I bought you a coffee.
