### ISSUE TITLE
Videos without the "controls" parameter breaks

### ISSUE THREAD

**Issue by optimocha** [verlok/vanilla-lazyload#565]
**Describe the bug**
`<video>` tags without the `controls` parameter isn't recognized by the lazy load script, so the `data-src` parameter isn't converted to `src`.

**To Reproduce**
Deleting the `controls` parameters in the video lazyload example code would reproduce the problem.

**LazyLoad version**
Latest.

**Comment by optimocha** [comment]
Scratch that, it's working. Feel free to delete this issue completely.

**Comment by verlok** [comment]
Hey @optimocha 
I’m glad you solved!

If you’re happy with the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
