### ISSUE TITLE
An option to set a callback function which is called whenever an element finishes loading/triggers an error/loading is canceled

### ISSUE THREAD

**Issue by ExLuzZziVo** [verlok/vanilla-lazyload#567]
Hi,

I have another idea that can be used to avoid code duplication and make it cleaner when using your awesome plugin.

Is it possible to add the `callback_completed` event that fires whenever an element finishes loading/triggers an error/loading is canceled?

Before:
```js
const lazyLoad = new LazyLoad({
    callback_loaded: (el) =>
    {
        // Some actions

        onCompletedFunction(el);
    },
    callback_cancel: (el) =>
    {
        // Some actions

        onCompletedFunction(el);
    },
    callback_error: (el) =>
    {
        // Some actions

        onCompletedFunction(el);
    }
)};
```
After:
```js
const lazyLoad = new LazyLoad({
    callback_loaded: (el) =>
    {
        // Some actions
    },
    callback_cancel: (el) =>
    {
        // Some actions
    },
    callback_error: (el) =>
    {
        // Some actions
    },
    callback_completed: onCompletedFunction
)};
```

**Comment by verlok** [comment]
Hey @ExLuzZziVo ,
of course, everything is possible.

Thank you for explaining that with some JS code, but can I ask you a question to understand better your use case?

Why you would need to execute the same code both when an image was loaded OR its loading was cancelled OR it threw an error? These three seems to me very different cases which one would need to handle with different code.

In other words, what that `onCompletedFunction` would do for you?

**Comment by ExLuzZziVo** [comment]
Hi @verlok,

The closest analogue to `onCompletedFunction` is `finally` code block in `try {} catch {} finally {}`.

The simplest example:
There is an image that is lazy loading and a _hidden_ delete button in the top right corner. This button should be shown to the user after the image load is completed or failed.

**Comment by verlok** [comment]
Understood. 
This sounds sensible to me. 

But why would you want it to be triggered if the loading was cancelled?

**Comment by ExLuzZziVo** [comment]
@verlok
Sorry, I misunderstood the documentation about the cancellation. There is no need to trigger it if the loading was cancelled.

**Comment by verlok** [comment]
I wouldn’t do what you suggested then, it’s not a big deal to call a function twice in your code, and it would create confusion in LazyLoad code because there are many other callbacks beyond load and error. Thanks anyway for your suggestion.
