### ISSUE TITLE
Set a different background-image based on the viewport width

### ISSUE THREAD

**Issue by chocolata** [verlok/vanilla-lazyload#569]
Lazyload works great for background-images, but it would be great to set a different background-image based on the viewport width.

In pure CSS we could do the following:
```
.slide {
  background-image: url('portrait.jpg');
}
@media (min-width: 768px) { 
  .slide {
    background-image: url('landscape.jpg'); 
  }
}
```
But as we feed the background-image directly on the element via the `data-bg` attribute, this functionality seems to be lost (unless I'm mistaken?).

```
<div class="slide" data-bg="landscape.jpg"></div>
```

I mistakenly thought this would be solved by the recent implementation of `image-set()`, but `image-set()` does not seem to support `viewport-width` as a secondary parameter. 

Does anyone have an idea if it would be feasible to have a portrait image on mobile (based on a custom breakpoint), and a landscape image on desktop (based on another custom breakpoint)?

Botched JsFiddle, erroneously using image-set(), here:
[https://jsfiddle.net/nrvoLuz6/2/](https://jsfiddle.net/nrvoLuz6/2/)

_Originally posted by @chocolata in https://github.com/verlok/vanilla-lazyload/issues/543#issuecomment-1108708857_

**Comment by verlok** [comment]
Hey @chocolata 
thank you for starting this new thread. 

This LazyLoad library I’m has historically focused more on the content images than the background images, but now that lazy loading of content images is supported natively (with many limitations) and background images are very popular in web design, I’d say I could try and implement the feature you described.

My idea would be to have a different data attribute like `data-bg-responsive` where you could specify a set of media queries and related background image. 

Something like: 

```
data-bg-responsive="(min-width: 1920px) url(bgWide.jpg), (min-width: 768px) url(bgMedium.jpg), url(bgNarrow.jpg)
```

The first matching media query would win and the related background image would be used. Background images could be urls or gradients. Media queries could be based on min-width or any else expression to pass, including orientation. 

What do you think?

**Comment by chocolata** [comment]
Hi @verlok 

Thanks for your reply and sorry for my late reaction. Hectic days here at the moment.

I think your proposed solution with the `data-bg-responsive` attribute would be a good idea. 

I was looking at the sizes attribute of the srcset functionality on images, but in our use case, I think it would be too confusing. I think we have to make it very clear that that functionality isn't compatible with this new functionality.

Question: would `data-bg-responsive` listen for resize events on the window or rotation of the device? That would be necessary I think.

Let me know if I can help out in any way shape or form.
Thanks again.

**Comment by verlok** [comment]
Yes, you're right, listen for resize events on the window or rotation of the device would be necessary.
And adding a resize listener is beyond the scope of this script.

That's why I'm afraid I won't implement this feature.
Sorry, that would really be beyond scope.

**Comment by chocolata** [comment]
We'll just have to wait untill the image-set() functionality supports device width I guess...
