### ISSUE TITLE
background image callback_error demo is not correct

### ISSUE THREAD

**Issue by Soul244** [verlok/vanilla-lazyload#573]
**Is your feature request related to a problem? Please describe.**
background images demo is not correct for callback_error function. 

https://github.com/verlok/vanilla-lazyload/blob/master/demos/background_images.html

If you are using an image as background-image, you have to set your fallback image to style.backgroundImage property of that element. So, we should change this example.

**Describe the solution you'd like**
 
```js
callback_error: (element) => {
       const name = element.tagName.toLowerCase();
      if (name === 'img') {
        element.setAttribute('src',  "https://via.placeholder.com/220x280/?text=Error+Placeholder");
      } else {
        element.style.backgroundImage = "url('https://via.placeholder.com/220x280/?text=Error+Placeholder')";
      }
  },
```

By this example, we are setting src of element if that element is an image, otherwise we are setting backgroundImage property.

**Describe alternatives you've considered**
or just change it with this:

```js
element.style.backgroundImage =  "url('https://via.placeholder.com/220x280/?text=Error+Placeholder')";
```

**Comment by verlok** [comment]
Hey @Soul244,
thank you for pointing this out, I changed the 3 demos with background images and released a new minor. 
I also tagged you and this issue in the release notes.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
