### ISSUE TITLE
Many requests get cancelled, why?

### ISSUE THREAD

**Issue by baszero** [verlok/vanilla-lazyload#574]
**Is your support request related to a problem? Please describe.**
When I scroll down a page VERY slowly and observe how the images are loaded lazy, I still see a lot of cancelled requests, why?
Once in a while I also observed that resources get requested and cancelled in a loop, even though I'm not touching my computer. 

**Expected behavior**
I am the opinion that when I scroll very slowly, no single cancelled request should occur.

**LazyLoad version**
17.8.2

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser Chrome 101.0.4951.54

**Screenshots**
![image](https://user-images.githubusercontent.com/596855/171160512-a977a420-5ac5-4877-9e29-a6d58055d118.png)

**Comment by verlok** [comment]
Hey @baszero ,
thank you for opening this, and sorry for the delay in this reply.

I am unable to reproduce the issue in any of the demos provided with the script.
[Check the basic images demo](https://www.andreaverlicchi.eu/vanilla-lazyload/demos/image_basic.html) for example.

How can I reproduce your issue, so that I can debug and help you?

**Comment by baszero** [comment]
Hi verlok, many thanks. by "shape" you mean the dimensions? All images have no width and height, as they are not known, the will fit responsively into the div where the img gets loaded. I will try the cancel_on_exit option. Thanks!

**Comment by baszero** [comment]
Hi verlok, with the property cancel_on_exit set to true I could also see a beheaviour where it causes a never ending loop. These requests actually hit my local web server, overloading it with requests. I now set the option cancel_on_exit to FALSE and this behaviour can not be observed anymore.

unfortunately I can not create a demo where this is always reproducible. I managed to observe it by setting the throttling option in Chrome to "3G Slow", I scrolled fast down, the up very slowly, suddenly the loop started...

**Comment by verlok** [comment]
Hey @baszero,

> with the property cancel_on_exit set to true I could also see a beheaviour where it causes a never ending loop.

I can understand, because that doesn't change the default value of `cancel_on_exit`, which is `true` by default.
If you want to disable the requests canceling when exiting the viewport, you shall set it to `false`.

So:

```js
  cancel_on_exit: false
```

Would you try with this setting?

**Comment by verlok** [comment]
Let me know if you solved the issue already, with my (late, sorry) comments or in some other way.

**Comment by lzlife** [comment]
Hello, I also encountered this problem, and it seems to be stuck between entering the view and canceling the view, and then repeatedly loading and canceling the status. I try to cancel_ on_ Change exit to false to solve this problem

**Comment by lzlife** [comment]
Hello, I also encountered this problem, and it seems to be stuck between entering the view and canceling the view, and then repeatedly loading and canceling the status. I try to 'cancel_on_exit' is modified to '0' to solve this problem

**Comment by verlok** [comment]
Hey @lzlife,

yes you could set the parameter `cancel_on_exit` to `false` to solve the issue, let me know if it works for you. 

The best solution though, to optimise performance and make sure [CLS](https://web.dev/cls) stays to the minimum, would be to leave `cancel_on_exit` to its default value (`true`) and make sure that the images have the same shape before they are loaded from LazyLoad. - You can do that by setting the width and the height attributes to the images elements to values that represent the image proportions.

**Comment by verlok** [comment]
@baszero any news from your side?

**Comment by verlok** [comment]
Hello @baszero @lzlife, 
it seems you don’t need support anymore.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
