### ISSUE TITLE
Click Scrollto issue with document.height

### ISSUE THREAD

**Issue by andresclua** [verlok/vanilla-lazyload#575]
**Is your support request related to a problem? Please describe.**
The "problem" is that when I click on the button, images are not loaded/shown, and therefore the anchor doesn't get where it should.

**To Reproduce**
https://codepen.io/andresclua/pen/OJvPeZV

**Expected behavior**
Ideally should be at the bottom of the page.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version [17.8.2]

**Desktop (please complete the following information):**
all devices

**Smartphone (please complete the following information):**
all devices

**Comment by Sysix** [comment]
Hey,
today you don't really need js to lazyload images. your browser can do that for you.
See this example: https://jsfiddle.net/aduqrms2/1/

Your root problem:
no height and width defined for the image. your browser don't know how much space they should be give the element.
Only height / width ratio is only really important (mostly you will override the width anyways with css). 

see following link for more: https://web.dev/browser-level-image-lazy-loading/

**Comment by andresclua** [comment]
hey @verlok 
I ended up doing that, thanks for your assistance!

**Comment by verlok** [comment]
Hey @andresclua,
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
