### ISSUE TITLE
callback_error type?

### ISSUE THREAD

**Issue by 500Foods** [verlok/vanilla-lazyload#576]
**Is your feature request related to a problem? Please describe.**
Using callback_error works great when handling certain kinds of errors, particularly HTTP 429 (too many requests) as it can be used to re-request the image at a slightly later time.  However, sometimes the error is HTTP 403 (forbidden) and this mechanism will continue to request the image and never actually succeed.

**Describe the solution you'd like**
An extra parameter in callback_error to indicate which error is being encountered, so appropriate actions can be taken.

**Describe alternatives you've considered**
I've tried adding onerror handling to the image itself but I think vanilla-lazyload handles it instead of the onerror function?

**Additional context**
This comes up when loading a batch of images (for example, from TMDb.org).  Sometimes one of the images is forbidden, but it keeps retrying to load that forbidden image.  Meanwhile, any 429's are requeued and eventually download fine when hitting a server with hundreds of simultaneous requests.  Just looking to not cause trouble with the 403's.

**Comment by verlok** [comment]
Really good idea, and it should be relatively easy to implement. Will do. Stay tuned.

**Comment by verlok** [comment]
Hey @500Foods ,
it looks like it's not feasible, since the error handler doesn't pass any more information about the error in the event object.

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/1127721/180070622-ff634c61-36fe-44f0-9ca9-e466b82b0045.png">

**Comment by verlok** [comment]
I mean I get the network error printed in the console, but that's normal, then if I try and look into the Event object returned by the error handler, I get a generic `type: "error"` and nothing more, so no HTTP status code, unfortunately

**Comment by 500Foods** [comment]
Hmm...  Alright. Disappointing.  How about instead we count errors for an image, so we can then check and say "hey, we've tried to get this image x times already, and it isn't happening, so let's stop trying"  where x is probably going to be something like 3 or 4 or 5.

**Comment by 500Foods** [comment]
And then we could tie the retries to a different time.  IE, wait for 1s on the first retry, 1.5s on the second retry, etc. just by picking up, say, an error-1 class and setting a timeout, with a different timeout for an error-2 class, and so on?

**Comment by 500Foods** [comment]
You can check out https://www.actorious.com for an example of where this comes up (try it from a desktop though). It contacts a CDN of some kind for the images and depending on which one it gets, they may have a rate-limit imposed.  So as you scroll through it requests more images (lazy loading all the way) but when it hits that rate-limit it slows down.  Which works perfectly until it hits some obscure forbidden image which it then tries to reload continuously.

**Comment by 500Foods** [comment]
I guess I could also just add the error counter class myself in the callback_error call.  Never thought of that until now 🤔

**Comment by verlok** [comment]
> I guess I could also just add the error counter class myself in the `callback_error` call.

Yes, that is what I was about to suggest :)

I want to leave `vanilla-lazyload`'s code as lightweight as possible so it's fast to download for who uses it directly from a CDN. 

The API is there to make any kind of customisation externally.

**Comment by verlok** [comment]
Can I do anything else for you?

**Comment by 500Foods** [comment]
No, thank you.  That'll address the problem I came in with pretty well I think.  Thanks!

**Comment by verlok** [comment]
Thank you for the initial idea @500Foods, it would've been a good enhancement, too bad it's not possible to implement it.

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
