### ISSUE TITLE
Version 17 doesn't overwrite `img`'s `src` when using `picture` (was: Migrating From 13.0.1 To 17.8.3)

### ISSUE THREAD

**Issue by kunimaru-personal** [verlok/vanilla-lazyload#579]
**Is your support request related to a problem? Please describe.**
In 17.8.3 when I use markups which work in 13.0.1 the browser won't load an image I expect.

**To Reproduce**
1. Write the html below

```html
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@13.0.1/dist/lazyload.min.js"></script>
</head>
<body>
<picture>
    <source data-srcset="https://via.placeholder.com/480x270.webp?text=Success" type="image/webp">
    <source data-srcset="https://via.placeholder.com/480x270.png?text=Success%20WebP%20Not%Supported" type="image/png">
    <img src="https://via.placeholder.com/480x270.png?text=Placeholder" data-src="https://via.placeholder.com/480x270.png?text=Fallback%20Image" width="480" height="270">
</picture>
<script defer>
new LazyLoad({});
</script>
</body>
```
2. Upgrade this package from 13.0.1 to 17.8.3
```html
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.8.3/dist/lazyload.min.js"></script>
</head>
<body>
<picture>
    <source data-srcset="https://via.placeholder.com/480x270.webp?text=Success" type="image/webp">
    <source data-srcset="https://via.placeholder.com/480x270.png?text=Success%20WebP%20Not%Supported" type="image/png">
    <img src="https://via.placeholder.com/480x270.png?text=Placeholder" data-src="https://via.placeholder.com/480x270.png?text=Fallback%20Image" width="480" height="270">
</picture>
<script defer>
new LazyLoad({});
</script>
</body>
```
3.  Source `https://via.placeholder.com/480x270.png?text=Placeholder` is loaded

**Expected behavior**
Source `https://via.placeholder.com/480x270.webp?text=Success` is loaded
Source Priority:
1. WebP
2. PNG (browser doesn't support WebP)
3. Placeholder (a network problem or something happens)

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.8.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 103.0.5060.134

**Comment by verlok** [comment]
Hey @kunimaru-personal ,
you are totally right! That looks like an undocumented change.

It happened between V16 and V17

If you try this with V16, it works

```html
<html>
<head>
<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@16.1.0/dist/lazyload.min.js"></script>
</head>
<body>
<picture>
    <source data-srcset="https://via.placeholder.com/480x270.webp?text=Success" type="image/webp">
    <source data-srcset="https://via.placeholder.com/480x270.png?text=Success%20WebP%20Not%Supported" type="image/png">
    <img src="https://via.placeholder.com/480x270.png?text=Placeholder" data-src="https://via.placeholder.com/480x270.png?text=Fallback%20Image" width="480" height="270">
</picture>
<script defer>
new LazyLoad({});
</script>
</body>
```

I will investigate on how that happened and if there's a solid reason behind it.

**Comment by verlok** [comment]
Hey @kunimaru-personal ,
I've found the issue, and... you need to review your code. 

The thing to do are well explained in the [UPGRADE.md](https://github.com/verlok/vanilla-lazyload/blob/master/UPGRADE.md). 
I recommend you to read that file that explains everything you need to do (if you need to do it) version by version.

---

You should add the `lazy` class to your lazy images.

```html
<!-- FROM -->
<img data-src="lazyImage.jpg" alt="Lazy image" />
<!-- TO -->
<img class="lazy" data-src="lazyImage.jpg" alt="Lazy image" />
```

**ALTERNATIVELY**, you could set the `elements_selector` option to `"img"`

```js
const myLazyLoad = new LazyLoad({
  /* other options here */
  elements_selector: "img" // ADD THIS OPTION
});
```

---

This should solve for you!
Let me know how it goes.

**Comment by kunimaru-personal** [comment]
> The thing to do are well explained in the UPGRADE.md.
It works perfectly.
I didn't know `UPGRADE.md` exists.
I'll read it well from next time.
Thanks so much!

**Comment by verlok** [comment]
Hey @kunimaru-personal, 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
