### ISSUE TITLE
Using in Vue components

### ISSUE THREAD

**Issue by Artem-Schander** [verlok/vanilla-lazyload#581]
**Is your support request related to a problem? Please describe.**
I have a Vue app which loads some images and puts them in a component. In said component Vanilla LazyLoad gets initialized on mount. Everything looks right at first glance, but the devtools network tab says that nearly all images are getting loaded immediately. only the ones in a slider (horizontally out of viewport) are getting loaded lazily.
I tried to change the `use_native` setting to `false` which made it worse. In that case nothing got lazyloaded. Every image got instantly loaded.

I think I must have made something wrong. Could someone tell me whats the problem here?

**To Reproduce**
It was not possible to recreate my use case in full extend, however here is a code sandbox
https://ghz6ww.csb.app/

**Expected behavior**
I would expect the images to be lazyloaded in both axes.

**LazyLoad version**
- Version 17.8.3

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 106.0.5249.103

**Comment by Artem-Schander** [comment]
BTW I've read all existing issues regarding Vue, there is nothing relevant for my case.

**Comment by Artem-Schander** [comment]
Ok, I think I got it.
I really should read the docs more carefully.
It's the container setting. 🤦 
Sorry for the noise.

**Comment by verlok** [comment]
Hey @Artem-Schander 
would you mind sharing what was the solution to this issue?

**Comment by Artem-Schander** [comment]
I initialized vanilla-lazyload with the `container` setting being set to the `div` containing the image itself.
Like so:
```vue
<template>
  <div class="lazy-picture" ref="container">
    <picture>
      <source :data-srcset="image.webp" type="image/webp" />
      <source :data-srcset="image.jpg" type="image/jpeg" />
      <img class="lazy" :data-src="image.jpg" width="640" height="320" />
    </picture>
  </div>
</template>

<script>
import LazyLoad from "vanilla-lazyload";

export default {
  name: "LazyPicture",
  props: {
    image: Object,
  },
  mounted() {
    new LazyLoad({
      container: this.$refs.container,
      use_native: false,
      threshold: 300,
    });
  },
};
</script>
```

I didn't know, that in this case `vanilla-lazyload` wouldn't pay attention to `getBoundingClientRect` being in the viewport or something similar.

As soon as I removed the `container` setting, everything worked just fine.

BTW. thanks for the lib. amazing work :) really nice to see devs consider the size of a resulting project.

**Comment by verlok** [comment]
Hey @Artem-Schander, 
Thank you for sharing your resolution. 

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
