### ISSUE TITLE
Nuxt 3 + Vanilla Lazyload: Images are not loaded after a second route visit

### ISSUE THREAD

**Issue by armin-salihovic** [verlok/vanilla-lazyload#582]
Hi! I'm trying to use vanilla-lazyload with Nuxt 3. After many hours of trying I was not able to get it working completely.
I do not understand why `lazyLoadInstance.value.update()` does not update the DOM in the `onMounted` hook, but works when calling it manually.

<h2>Problem description:</h2>
<ol>
    <li>On first route visit, the image initially loads fine.</li>
    <li>However, if you go to the <b>Page 2</b>, and then back to the <b>Page 1</b>, the <i>vanilla-lazyload</i> will not load the image... :(</li>
    <li>If you call <i>lazyLoadInstance.update()</i> manually (with a button), then the image will get loaded.</li>
</ol>

<h2>Code:</h2>

layouts/default.vue
```vue
<template>
  <div>
    <slot></slot>
  </div>
</template>
```

pages/index.vue
```vue 
<template>
  <div>
    <div class="container">
      <h1>Page 1</h1>
      <NuxtLink to="/page-2">Open Page 2</NuxtLink>
      <img class="lazy" src="/placeholder.jpg" data-src="/image.jpg" alt="Lazy image">
    </div>
    <button @click="lazyLoadInstance.update()">Update</button>
  </div>
</template>

<script setup>
import LazyLoad from "vanilla-lazyload";

const lazyLoadInstance = ref();

onMounted(async () => {
  lazyLoadInstance.value = new LazyLoad();
  // does not work
  lazyLoadInstance.value.update();
});
</script>

<style scoped>
.container {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  padding-bottom: 1rem;
}
img {
  width: 300px;
}
</style>
```

pages/page-2.vue
```vue 
<template>
  <div>
    <h1>Page 2</h1>
    <NuxtLink to="/">Return to Page 1</NuxtLink>
  </div>
</template>
```

app.vue
```vue 
<template>
  <NuxtLayout>
    <NuxtPage />
  </NuxtLayout>
</template>
```

package.json
```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.12"
  },
  "dependencies": {
    "vanilla-lazyload": "^17.8.3"
  }
}
```

**Comment by verlok** [comment]
I never used nuxt, se you sure that you need to use the ` value ` keyword there?

```JS
lazyLoadInstance.value.update();
```

You’re not using it in the button click handler, I noticed, but maybe it’s supposed to be like that.

**Comment by armin-salihovic** [comment]
Thank you for the reply! 

Yes, the usage of the `lazyLoadInstance` variable is correct.

That is the new way of creating and accessing reactive variables in the Vue 3 composition API: 
- https://vuejs.org/guide/essentials/reactivity-fundamentals.html#reactive-variables-with-ref
- https://vuejs.org/api/reactivity-core.html#ref

I also tried the [lazysizes](https://github.com/aFarkas/lazysizes) package, and it does not seem to have this problem, i.e., it loads the images regardless of whether the route was accessed for the first time or the second.

**Comment by pzpsofficial** [comment]
@armin-salihovic Were you able to solve this issue? I'm facing the same problem with my Nuxt 3 website.

**Comment by armin-salihovic** [comment]
> @armin-salihovic Were you able to solve this issue? I'm facing the same problem with my Nuxt 3 website.

Unfortunately, no. I ended up going with the [lazysizes](https://github.com/aFarkas/lazysizes) package as it does not have this problem.

**Comment by pzpsofficial** [comment]
@armin-salihovic Thanks! I've also ended up using another package.

**Comment by wokalek** [comment]
@armin-salihovic 
@pzpsofficial 

Have this issue and I handled this with that:

```ts
const picture = ref<HTMLPictureElement>()

onMounted(() => {
  const images = document.querySelectorAll<HTMLImageElement>(`#${picture.value?.id} img`)

  images[0].addEventListener('load', () => {
    $lazyLoad.update(images)
  })
})
```

Now we waiting load of preview placeholder from `src` from `<img>` element, and after that we call `update` of vanilla-lazyload API.

**Comment by verlok** [comment]
Thanks for the support, @wokalek!
That solution looks good to me.
