### ISSUE TITLE
Does hybrid lazy load still have to use data-src? what makes it better than adding the loading='lazy' attribute manually?

### ISSUE THREAD

**Issue by dwipras-exe** [verlok/vanilla-lazyload#583]
I want to try using hybrid lazy loading because I don't really like using the data-src attribute. But I still want to use the data-bg attribute to load the background image.

Now, I have enabled use_native: true. Become:

```
const lazyContent = new LazyLoad({
   use_native: true,
...
});
const lazyBackground = new LazyLoad({
   ...
});
```

This technique is successful in adding elements with the loading='lazy' attribute automatically. But the effect doesn't work like when we add the loading='lazy' attribute manually. It doesn't work completely if I use src instead of data-src.

Even though I want to use hybrid because I don't really like the data-src attribute. Any solution using hybrid loading without using the data-src attribute?

Should I leave the hybrid and enter the loading='lazy' attribute manually instead?

**Comment by verlok** [comment]
Back in 2019, as browsers were just starting to support native lazy loading, I [defined](https://www.smashingmagazine.com/2019/05/hybrid-lazy-loading-progressive-migration-native/) hybrid lazy loading a technique to progressively switch from JS lazy loading to native lazy loading, by using `data-src` and using JS to enable native lazy loading in browsers which supported it.  

Now it’s 2022 and, unless you need callbacks or you want to really optimise web performance, for content images you can use `src` and `loading=lazy`, without `data-src`. That is not hybrid lazy loading, that is native lazy loading, and it will work in every browser that support it. You don’t need JavaScript, so no `const lazyContent = new LazyLoad({use_native: true});`. 

For background images you still need the `data-bg` attribute and the `const lazyBackground = new LazyLoad(…);` as browser don’t support it. 

To answer the questions in the title of this issue:

> Does hybrid lazy load still have to use data-src? 

Yes, but you don’t need hybrid lazy loading, at least in the way I mean it. 

> what makes it better than adding the loading='lazy' attribute manually?

Nothing, if you want to enable native lazy loading with `use_native`. If you don’t. Using JS driven lazy load has the following advantages:
- it really hides images to the browser until JavaScript kicks in, which might improve web performance, in terms of largest contentful paint
- on slow connections and pages with lots of images, if users scroll down fast, it optimises to focus on the images on screen, candeline the download of the ones gone off screen
- it triggers callbacks, if you need them to control stuff related to images entering/exiting the viewport or loading/loaded/triggered an error. 

Does this answer solve your issue?

**Comment by verlok** [comment]
You inspired me to write this blog post:
[Do we still need lazy loading libraries and `data-src` in 2022?](https://www.andreaverlicchi.eu/do-we-need-hybrid-lazy-loading-in-2022/)

**Comment by verlok** [comment]
I’ve changed the link of the article. It’s now https://www.andreaverlicchi.eu/do-we-need-lazy-loading-libraries-data-src-in-2022/

**Comment by verlok** [comment]
Hey @dwipras-exe,

do you still need help with this issue?
 If not, how did you solve?

**Comment by dwipras-exe** [comment]
Thank you very much for the detailed explanation, in the end I still use this library because of its stronger power.

**Comment by verlok** [comment]
Hey @dwipras-exe, 
I’m glad you liked the explanation and you still use my library!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
