### ISSUE TITLE
Advisable to use the decoding async attribute?

### ISSUE THREAD

**Issue by bridgeport** [verlok/vanilla-lazyload#584]
First, thanks for this great script.

Is it advisable to use the decoding async attribute on image tags along with vanilla lazyload?

I searched for this topic as far as I could and found no information. I even checked other JavaScript lazyload libraries, and no issues referenced the term "decoding"

More about the optimization standard may be read here:

https://mediajams.dev/post/asynchronously-load-and-decode-images
https://fantinel.dev/web-images-modern-formats/

WordPress 6.1 has added the `decoding="async"` attribute to all images, so it'll become more prevalent.

Thanks.

**Comment by verlok** [comment]
It is a topic currently under research in the web performance community. At the moment, they didn’t notice much of a difference when using it and not. Therefore, I don’t think it makes much of a difference especially if the images are lazy loaded via Javascript.
