### ISSUE TITLE
img still loading if XMLHttpRequest is running and finished

### ISSUE THREAD

**Issue by AozoraDev** [verlok/vanilla-lazyload#586]
**Describe the bug**
If you do an XMLHttpRequest while some images are loading, then the images will still loading even though the XMLHttpRequest execution is finished.

**To Reproduce**
1. Run XMLHttpRequest while some images still loading

**Expected behavior**
Lazyloading img can be completed.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.8.3

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chromium
 - Version 109

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 8.1
 - Browser Chrome
 - Version 105.0.5195.136

**Screenshots**
![IMG_20230126_230404](https://user-images.githubusercontent.com/61007475/214870750-639e7c4a-905a-4037-80f8-c54d8ac5a1cc.JPG)

**Additional context**
...

**Comment by verlok** [comment]
Hi @AozoraDev 
thank you for opening this issue. 

I’m going to need more information on
> Run XMLHttpRequest while some images still loading

- What XMLHttpRequest are you running?
- What code are you using to run it?
- When are you running it?

Moreover, it would be nice to reproduce the problem in a codepen, to be sure that there aren’t any other factors interfering.

**Comment by AozoraDev** [comment]
Hi!
Here's the quick example to reproduce this issue.
Hope it'll answer questions above.

https://codepen.io/AozoraDev/pen/zYLayxy

**Comment by AozoraDev** [comment]
Try to scroll it faster and don't stop...
And.... make sure the images still loading.

**Comment by binaryfire** [comment]
I'm having the same issue too. Any idea for a workaround?

**Comment by verlok** [comment]
@AozoraDev I took a look at your codepen. The XMLHttpRequest is running at every scroll then you use the response URL to append an `img` element using `container.innerHTML += something`. This is probably the source of the bug. Appending to the `innerHTML` of a container is not how you append DOM elements to the page. Could you explain why are you doing that, instead of using the `appendChild` method?

**Comment by verlok** [comment]
@binaryfire what is your use case? Can you provide HTML and JS code? Are you also using `.innerHTML += something` to append new DOM to the page?

**Comment by binaryfire** [comment]
@verlok Thanks for the quick reply. It's happening in a Laravel Livewire app (Livewire actions are XHR requests). There's no custom JS involved. Let me dig a bit deeper and get back to you with more info.

**Comment by verlok** [comment]
@binaryfire. Livewire docs says it does the following:

> Livewire renders the initial component output with the page (like a Blade include). This way, it's SEO friendly.
> When an interaction occurs, Livewire makes an AJAX request to the server with the updated data.
> The server re-renders the component and responds with the new HTML.
> Livewire then intelligently mutates DOM according to the things that changed.

That "intelligently mutates DOM" looks good to me.

You just need to make sure that you're calling the `update()` method on your `LazyLoad` instance after Livewire has added the new DOM, to make LazyLoad aware that there's new DOM added to the page.

Check the [dynamic content section in the README file](https://github.com/verlok/vanilla-lazyload#dynamic-content) to know more.

**Comment by AozoraDev** [comment]
> @AozoraDev I took a look at your codepen. The XMLHttpRequest is running at every scroll then you use the response URL to append an `img` element using `container.innerHTML += something`. This is probably the source of the bug. Appending to the `innerHTML` of a container is not how you append DOM elements to the page. Could you explain why are you doing that, instead of using the `appendChild` method?

@verlok 
Welp, in my case... The request is not return image URL but a whole HTML code, so probably using appendChild is impossible.

**Comment by verlok** [comment]
I understand @AozoraDev, but in that case you didn't provide the right code in the codepen you created. And I don't think the bug you're having is due to LazyLoad. This library is used by so many sites that if there was a similar bug, it would be full of issues here.

**Comment by verlok** [comment]
@binaryfire did you manage to solve?

**Comment by AozoraDev** [comment]
> I understand @AozoraDev, but in that case you didn't provide the right code in the codepen you created. And I don't think the bug you're having is due to LazyLoad. This library is used by so many sites that if there was a similar bug, it would be full of issues here.

Welp, i think the problem is not from how new element added.
Like i said, when a image is still loading and XMLHttpRequest is executed, that loading image will still stay in loading state after XMLHttpRequest return response.

**Comment by verlok** [comment]
Can you reproduce the issue by initiating an XMLHttpRequest while images are downloading in one of the demos provided in the demos folder of this repository?

**Comment by binaryfire** [comment]
> @binaryfire did you manage to solve?

@verlok I did. Looks like it was a weird quirk with my local dev environment. All good now, thanks.

**Comment by verlok** [comment]
Hey @binaryfire, 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
