### ISSUE TITLE
Data-bg-set not working as expected

### ISSUE THREAD

**Issue by michaelbutler1998** [verlok/vanilla-lazyload#594]
**Describe the bug**

Using data-bg works fine, the image is set as a background image.

Using data-bg-set does not. Even when only including one image within the set, the same image used with data-bg, the image does not appear (the container's background remains blank). The lazy class adds the "entered" class, but does not add the image.

**To Reproduce**

I've created a code pen with the minimum reproducible - https://codepen.io/michaelbutler1998/pen/WNajZGJ

**Expected behavior**
The background image should be added to the red outlined box within the codepen using both data-bg and data-bg-set

**LazyLoad version**

CDN - https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.8.3/dist/lazyload.min.js

**Desktop (please complete the following information):**

Chrome browser on Mac

**Smartphone (please complete the following information):**
N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/15836316/234529531-c1e4691c-c028-459b-8eba-2e2bf2766a02.png)

**Comment by verlok** [comment]
Hey @michaelbutler1998 ,
thank you for reaching out. 

The `data-bg-set` is a feature that can work with multiple types of background images, including browser generated gradients, therefore its value requires a different syntax, as stated in the documentation (README file). 

Looking at your codepen, you seem to be missing `url()` in the `data-bg-set` value. 

Please read the documentation, add that, and let me know if this solves your issue.

**Comment by michaelbutler1998** [comment]
Morning @verlok, apologize I should have added examples with the URL wrapper and URL wrapper with quote marks to show that this also was not working, I have added these examples now to the original code pen.

**Comment by verlok** [comment]
Hey @michaelbutler1998 ,
you are missing the equal sign in your markup

You have
```
data-bg-set"url('https://..."
```

Should be
```
data-bg-set="url('https://..."
```

**Comment by michaelbutler1998** [comment]
@verlok you're correct, I've amended this, the issue is still present

**Comment by verlok** [comment]
It's not.
https://codepen.io/verlok/pen/OJBgGye?editors=1000

**Comment by verlok** [comment]
Please not that if you're only looking for a way to have multiple background images, independently from the screen density, you might be looking for `data-bg-multi`.

See [this section](https://github.com/verlok/vanilla-lazyload#lazy-background-image) in the documentation.

**Comment by michaelbutler1998** [comment]
Thank you very much for your help @verlok 

I'm looking for the background equivalent of the below to set the BG img depending on width, so I think data-bg-set is the solution I'm after
```
data-srcset="lazy_400.jpg 400w, 
    lazy_800.jpg 800w"
```

**Comment by verlok** [comment]
Yes, that's the one

**Comment by verlok** [comment]
Well well @michaelbutler1998, I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
