### ISSUE TITLE
Support for media queries for lazy loading videos using <source /> tag.

### ISSUE THREAD

**Issue by gauravsaini964** [verlok/vanilla-lazyload#596]
**Is your feature request related to a problem? Please describe.**
Having two different videos for mobile and desktop is painful to implement. Using lazy load to implement videos in my website, it would be lovely to have media queries support in the library inbuilt.

**Describe the solution you'd like**
Similar to the solution we have in picture tag. Different source based on different screen sizes.

**Describe alternatives you've considered**
Implementing in react but seems redundant as we are already using vanilla-lazyload and it does awesome job.

**Comment by verlok** [comment]
I've googled, and there's actually a W3C specification for the `media` attribute in the video element. 
http://www.w3.org/TR/2014/REC-html5-20141028/embedded-content-0.html#attr-source-media

So now the question is: why browsers have not implemented it like in the W3C specs?

**Comment by verlok** [comment]
Uh, it's in the `video` element and not in the `source` tags like in the case of images. I guess that's because of how they implemented source in `video` and in `picture`. The plot thickens.

**Comment by gauravsaini964** [comment]
I understand the issue for above-fold-content being lazy loaded. Right now there is no solution for it since browsers are not supporting media-queries in source tag all together. I doubt they will change it anytime soon. I do not render videos above fold because of performance considerations.

Cant we add support for this in this library and mark it as Dangerous and add warnings for above-fold-content ?

**Comment by verlok** [comment]
@gauravsaini964 have you tried searching if there's something like that?

**Comment by verlok** [comment]
And most importantly, @gauravsaini964 , you said you use React, have you tried using media queries with React hooks to generate the correct code for the video depending on the media query?

**Comment by verlok** [comment]
Closed because of inactivity.
