### ISSUE TITLE
The not transparent background is added when an image that has transparency.

### ISSUE THREAD

**Issue by palexandrite** [verlok/vanilla-lazyload#598]
**Describe the bug**
I have several background images which are png with transparency. 
And when I use vanilla-lazyload those images load with NO transparency.

**To Reproduce**
My setup of vanilla-lazyload:
```javascript
import LazyLoad from "vanilla-lazyload";

const lazyLoadInstance = new LazyLoad({
    // settings
    elements_selector: "[data-lazy-background]",
    data_bg          : "lazy-background",
    
    // Assign the callbacks defined above
    callback_enter   : callback_enter,
    callback_exit    : callback_exit,
    callback_cancel  : callback_cancel,
    callback_loading : callback_loading,
    callback_loaded  : callback_loaded,
    callback_error   : callback_error,
    callback_finish  : callback_finish
});
```

and images like:
```html
<div data-lazy-background="{{ asset('/img/main-page-foobar.png') }}" 
        class="md:hidden bg-no-repeat bg-contain bg-center h-80 mx-auto"></div>
```

**Expected behavior**
I would like to see those images with tranparency.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.8.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 116.0.5845.96

**Screenshots**

![2023-08-21_14-58-54](https://github.com/verlok/vanilla-lazyload/assets/19309630/9233c1a3-66b2-404f-8712-86227ab8cdcc)

**Comment by verlok** [comment]
Hey @palexandrite 
are you sure this issue is attributable to vanilla-lazyload?
I'm pretty sure vanilla-lazyload leaves the images untouched. 
What happens if you disable lazyloading?

**Comment by palexandrite** [comment]
Hi @verlok,
I deleted init code of vanilla-lazyload, clear cache of the browser, then got back init code, clear cache of the browser again, and... 
That effect disappeared!

I have done this many times, but the effect does not back after that disappearance. It was weird.

I would like to proposal to close this ticket :-)

**Comment by verlok** [comment]
Good to know @palexandrite, you likely had images with the wrong background in your browser cache.

I'm glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
