### ISSUE TITLE
Google bot unable to see image if offscreen horizontally

### ISSUE THREAD

**Issue by gengamer** [verlok/vanilla-lazyload#601]
**Describe the bug**
Normally, all images appear for Google bot after testing using Rich result test tool. Below the fold images also loaded, but if images are on Sliders that requires Horizontal scroll to view, it appears for users on Horizontal scroll, but for Google bot, src attribute still missing from one of my image.

My page contains 3 images on the sliders. Test it with Rich result test tool by Google. Then look at the view crawled page and HTML. Then search for https://bit.ly/3Ghsv6Y

Page to test if you want to check: https://bit.ly/47TsMc5

Here you can see only data-src and no src attribute as it horizontaly on left side. I tried rootMargin 500px 10000px, but nothing works.

**LazyLoad version**
Lazyload version used by Litespeed Cache Plugin. It looks like they modify some codes to show Console.log [Litespeed Lazyloaded] etc.

**Desktop (please complete the following information):**
 - OS: [Android, Windows]
 - Browser [chrome]
 - Version [Lastest chrome]

**Screenshots**
Not working image
![Screenshot_2023-11-26-11-16-26-369_com android chrome-edit](https://github.com/verlok/vanilla-lazyload/assets/108849445/a20d270f-daf1-465b-9750-e1d1f4488866)

Working image
![Screenshot_2023-11-26-11-17-33-575_com android chrome-edit](https://github.com/verlok/vanilla-lazyload/assets/108849445/a78fb0ce-eb52-433a-bbe3-9822e6d74aa0)

Until the bug not fixed, i am using Noscript tag for every images to make sure Google can crawl them.

**Comment by verlok** [comment]
Closing because the bug should be open on the litespeed plugin, as they should be using the latest version of vanilla-lazyload. Plus, the links you provided don't work anymore.
