### ISSUE TITLE
Delay default and source images loading issue

### ISSUE THREAD

**Issue by asyba** [verlok/vanilla-lazyload#603]
I notices recently that my setup is not working as expected.
I have a default image and then the one loading from external services with lazyload.
The problem is that the default image is not showing and it just showing empty space and then it shows the external image.

I notice this also on the Demos websites, if you scroll down fast you can see white space with no default image, and after some seconds it load the external image and never the default was used.

https://verlok.github.io/vanilla-lazyload/demos/image_ph_inline.html
https://verlok.github.io/vanilla-lazyload/demos/image_ph_external.html
(Note: try disable browser cache to test it)

Or maybe this is a normal behavior when images load fast there is no time to show the default image or both default/external image have the same delay of loading.

**Comment by verlok** [comment]
Hello,
thank you for your question.
I fail to understand what you mean by "default image" and "external image".
Could you specify that?

**Comment by verlok** [comment]
In the demos you linked, the placeholder image is only an empty SVG*, that's why you can't see it before the lazy image is loaded. 

*this is an old technique to reserve space for the image before it was loaded, now you should just use the `width`/`height` attribute on the image to so.

**Comment by asyba** [comment]
@verlok default image = "src" attribute on the img tag.
 external image = "data-src" attribute on the img tag.
 
 Mi project:
 I have a table with 500 images. but only are displayed 50 per pagination.
 each image is unique so while waiting on loading those 50 I want to show a default image.
 Sometimes it shows the default image before the external one, but other time it just show empty space and few seconds later  it load the external image.

**Comment by verlok** [comment]
I'd really need to see your HTML, CSS and JS code to be able to respond to your inquiry.

**Comment by verlok** [comment]
Or if you could share a link to CodeSandbox, CodePen with your code, that would help.

**Comment by asyba** [comment]
@verlok 
here you can check public page: https://deals.blu-raydar.com.ar/

(is on development, so any bug or feedback I will appreciate)

**Comment by verlok** [comment]
OK. Thanks. I won't be able to look into it until next Monday though.

**Comment by asyba** [comment]
I also found that "Minimize [CLS](https://web.dev/cls) by occupy space beforehand"
"The best way to do that is to set both width and height attributes to img"
I did that but still is not reserved the space, or is conflict with something and is not properly working, but I couldn't  find the cause

**Comment by erikyo** [comment]
@asyba I guess you are missing the `display: block` to img tag. 👇

![css](https://github.com/verlok/vanilla-lazyload/assets/8550908/81ef3bc1-e7dc-4b55-b919-8318aa8365f1)

**Comment by verlok** [comment]
It looks like the `width` and `height` attributes are wrongly assigned.

<img width="421" alt="Screenshot 2024-04-18 at 16 37 29" src="https://github.com/verlok/vanilla-lazyload/assets/1127721/e77c668f-ce53-4e40-9238-3f3c55e5962f">

The image is 110 × 138 px, but the image tag sets `height="120" width="110"`.
So the correct attributes values are `height="110" width="138"`.

**Comment by verlok** [comment]
@asyba do you still need the assistance on the main topic of this thread?
If yes, are you able to recap what's the issue you need help with?

**Comment by verlok** [comment]
Hey @asyba, 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the last 9 years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or even [sponsor me](https://github.com/sponsors/verlok), if you're a big fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day and weekend!
