### ISSUE TITLE
With double class the lazyload script does not work

### ISSUE THREAD

**Issue by peterhulst** [verlok/vanilla-lazyload#604]
**Describe the bug**
I have a class defined for an image, e.g.: <img class="logo-img" src=".
The lazyload script does not work.

**To Reproduce**
1. Javascript used: lazyload.min.js
2.<img class="logo-img" src=" ... is changed to:
   <img class="logo-img" class="lazy" data-src="....
2. The lazyload script does not display the image
3. Remove class="logo-img". This gives: <img class="lazy" data-src="....
4. The lazyload script works and the image is displayed lazy

**Expected behavior**
With none or an extra class(es) the lazyload should work always.

**LazyLoad version**
Please report which version of LazyLoad you're using.
- Version 17.8.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: EDGE (121.0.2277.98), FF (122.0)

**Comment by verlok** [comment]
Hey @peterhulst, could you provide the full HTML of your lazy images, and the JS code you're using to initialise this lazyload library?

**Comment by peterhulst** [comment]
[GitHub-Example.txt](https://github.com/verlok/vanilla-lazyload/files/14201596/GitHub-Example.txt)
Hello,

See file in appendix.
 
With **class="logo-img" class="lazy"** the image is not loaded. 
When replaced by only **class="lazy"**, the image is displayed correctly.
Also for:  **class="" class="lazy"**, the image is not loaded.

Regards,
Peter

**Comment by verlok** [comment]
Hey @peterhulst,
thank you for sharing the example. 

So you have a double class attribute in your image tag?
I don't think that's even allowed in HTML. 

I mean, maybe browsers still make it works because they're resilient, but when it comes to manipulating class names with JavaScript, then it might break because... which one should be updated? 

Try again by putting both class names in the same class attribute. 

For example, instead of 
```html
<img ... class="something" class="lazy">
```

do
```html
<img ... class="something lazy">
```

**Comment by peterhulst** [comment]
Hey!
You are completely right. 
When the first class is "lazy" (class="lazy"  class="logo-img") the lazyload works perfectly.
I agree that class="lazy logo-img" is the best (and correct) syntax. Also class="logo-img lazy " works (I checked both).
Thanks!
Regards,
Peter

**Comment by peterhulst** [comment]
I have closed it, because it is no bug.

**Comment by verlok** [comment]
Hey @peterhulst, 
I’m glad you solved!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or [sponsor me](https://github.com/sponsors/verlok), if you're a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
