### ISSUE TITLE
Probably unneeded babel transformation

### ISSUE THREAD

**Issue by erikyo** [verlok/vanilla-lazyload#611]
> Unrelated, but this is probably not needed anymore (nor in babelrc)

_Originally posted by @XhmikosR in https://github.com/verlok/vanilla-lazyload/pull/607#discussion_r1544575575_

Object.assign is widely supported, seems that isn't needed anymore. (ref. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#browser_compatibility)

Leveraging of this update the module size could be reduced and the syntax should be nicer

**Comment by XhmikosR** [comment]
AFAICT since you are using preset-env, assuming you have a proper browserslist config, it should pick up the plugins for you automatically.
