### ISSUE TITLE
Add back CHANGELOG.md

### ISSUE THREAD

**Issue by stanleyxu2005** [verlok/vanilla-lazyload#616]
**Is your feature request related to a problem? Please describe.**
In recent releases, the `CHANGELOG.md` is removed. It's a bit inconinient to see what's new in the package.

**Describe the solution you'd like**
Could you please add it back when publishing to npm registry?

**Describe alternatives you've considered**

**Additional context**
I tried to provide a PR, simply adding `"CHANGELOG.md"` into `package.json` > `files` sections. But I dont `README.md` there but it does exist in my local installed package. So I'd be appreciate that author to consider add it back.

**Comment by verlok** [comment]
Hey @stanleyxu2005,
the only files shipped with the `npm` installation were, historically, I've just checked the `package.json` of past versions, only the following

```json
  "files": [
    "dist",
    "typings"
  ],
```

There was recently a discussion on what to ship with `npm install`, for same reason we wanted to ship more files and we did in 19.0.3, but then somebody else made me think again and I rolled back that change in 19.0.5.

Ultimately, you can always read the change log [here on GitHub](https://github.com/verlok/vanilla-lazyload/blob/master/CHANGELOG.md), and also in the [Releases](https://github.com/verlok/vanilla-lazyload/releases/) page of this repo, so there's no need to install it on loca machines. 

Do you see any advantage of shipping it in with the `files` shipped via `npm`?

**Comment by stanleyxu2005** [comment]
As a user, when I run `npm outdated`, I will see packages with new versions. Unless it's major version change, otherwise I will upgrade no brainer. After it is installed, I'm couious about what has been changes. The quickest way in IDE is 
1. Open `package.json`
2. Ctrl + Click on the specified package to goto the installed package in `node_modules`
3. Find a `CHANGELOG.md`

If there is no such a file there, then 
1. I will have to open package's `package.json` 
2. Navigate to the homepage 
3. If there is a `CHANGELOG.md` then I will read, otherwise I will goto release page to see the changes. (e.g. `webpack`)

To me, `CHANGELOG.md` is part of a release, which should stay together. 
Looking at somewhere else is a bit "disconnected".
As you already maintain a `CHANGELOG.md`, I dont see a strong reason why not to include it in a download package.

**Comment by verlok** [comment]
Understood, @stanleyxu2005, thanks for detailing that.
I didn't know the `npm outdated` command, and I agree with you that having a changelog in-place is much easier to find and read.
Will add it to the files to ship.

**Comment by verlok** [comment]
Done --> [19.1.3](https://github.com/verlok/vanilla-lazyload/releases/tag/19.1.3)

**Comment by verlok** [comment]
Hey @stanleyxu2005,
thank you for your contribution!

If you’re happy with my support, the documentation and the effort I’ve been putting on this project in the latest years, I hope you might want to [buy me a coffee](https://ko-fi.com/verlok) to show your appreciation. Or even [sponsor me](https://github.com/sponsors/verlok), if you're really a fan.

Open-source software is great for everyone, but it takes passion and time (and coffee!) to grow and evolve.

Thank you for thinking about it. 
Have a wonderful day!
